-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 11, 2022 at 09:07 AM
-- Server version: 5.5.27
-- PHP Version: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `checklist_pn`
--

-- --------------------------------------------------------

--
-- Table structure for table `b`
--

CREATE TABLE `b` (
  `no` int(11) NOT NULL,
  `area` varchar(50) NOT NULL,
  `penilaian` varchar(1000) NOT NULL,
  `area_zi` varchar(1000) NOT NULL,
  `a` varchar(10000) NOT NULL,
  `b` varchar(1000) NOT NULL,
  `c` varchar(1000) NOT NULL,
  `d` varchar(1000) NOT NULL,
  `e` varchar(1000) NOT NULL,
  `nilai_abcde` varchar(25) NOT NULL,
  `kriteria` varchar(50) NOT NULL,
  `keterangan` varchar(500) NOT NULL,
  `bobot_nilai` varchar(50) NOT NULL,
  `nilai` varchar(10) NOT NULL,
  `bobot` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `b`
--

INSERT INTO `b` (`no`, `area`, `penilaian`, `area_zi`, `a`, `b`, `c`, `d`, `e`, `nilai_abcde`, `kriteria`, `keterangan`, `bobot_nilai`, `nilai`, `bobot`) VALUES
(94, 'PANMUD PERDATA', 'Kelengkapan Berkas PK (Manual)', 'Area 2', '1. Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Kepatuhan waktu dalam pengiriman berkas\n    peninjauan kembali ke Mahkamah Agung\n    dalam waktu maksimal 30\n    hari setelah Jawaban/tanggapan atas alasan\n    PK (PERDATA)\n3. Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas PK', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(95, 'PANMUD HUKUM', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,48', ' -   ', 'Ringan'),
(96, 'PANMUD HUKUM', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(97, 'PANMUD HUKUM', 'Implementasi SOP', 'Area 2,5', '1. KPN sudah menetapkan SK tentang\n    pemberlakuan SOP yang dikeluarkan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(98, 'PANMUD HUKUM', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud hukum sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', 'Area 2,5', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(99, 'PANMUD HUKUM', 'Prosedur tata kelola arsip (lakukan uji petik, minimal 10 berkas)', 'Area 2', '1. Sudah menggunakan aplikasi SIPP\n2. Penataan berkas sudah sesuai\n     dengan penataan aplikasi SIPP\n3. Setiap pencarian berkas dapat\n     ditemukan kurang dari 5 menit\n4. Ada jadwal perawatan arsip\n5. Ruang arsip dilengkapi komputer', '1 item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(100, 'PANMUD HUKUM', 'Prosedur Peminjaman Berkas', 'Area 2,5', '1. Sudah ada SOP Peminjaman berkas oleh internal dan external\n2. Peminjaman berkas disetujui oleh panitera dan diketahui oleh Ketua Pengadilan\n3. Sudah ditetapkan batas waktu\n     peminjaman\n4. Peminjaman berkas tercatat dengan\n    baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(101, 'PANMUD HUKUM', ' Pelaporan perkara secara elektronik', 'Area 2,5', '1. Telah melaksanakan pelaporan\n     perkara secara lengkap sesuai\n     dengan SK Dirjen Badilum Nomor\n     2992/DJU/SK/HM.02.3/9/2019\n2.Telah melaksanakan pelaporan perkara tepat waktu\n    sesuai dengan SK Dirjen Badilum\n    Nomor 2992/DJU/SK/HM.02.3/9/2019 \n3. Data yang dikirimkan akurat dan dapat \n    dipertanggungjawabkan\n4. Telah dimonev', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '7', ' -   ', 'Sedang'),
(102, 'PANMUD HUKUM', 'Survey kepuasan masyarakat berdasarkan PERMENPAN No. 14 Tahun 2017 dan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021\n', 'Area 6', '1. Ada Tim survey\n2.Survey menggunakan aplikasi SISUPER dari Ditjen Badilum\n3. Survey dilakukan 4 kali setahun (per Triwulan)\n4. Laporan Hasil Survey sudah di monev (3 unsur terendah)\n5. Hasil evaluasi sudah  ditindaklanjuti\n6. Hasil survey sudah terpublikasi (website\n    dan di ruang PTSP)', '1 item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4-5  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '8,5', ' -   ', 'Berat'),
(103, 'PANMUD HUKUM', 'Pelaksanaan Survey Persepsi Anti Korupsi berdasarkan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021', 'Area 6', '1. Ada Tim survey\n2.Survey menggunakan aplikasi SISUPER dari Ditjen Badilum\n3. Survey dilakukan 4 kali setahun\n4. Laporan Hasil Survey sudah di monev (3 unsur terendah)\n5. Hasil evaluasi sudah  ditindaklanjuti\n6. Hasil survey sudah terpublikasi (website\n    dan di ruang PTSP)', '1 item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '8,5', ' -   ', 'Berat'),
(104, 'PANMUD HUKUM', 'Pelaksanaan Survey Harian berdasarkan SK Dirjen Badilum No.1230/DJU/SK/HM.02.3/4/2021', 'Area 6\niv.a', '1. Ada Tim survey\n2. Survey menggunakan aplikasi SISUPER dari\n    Ditjen Badilum\n3. Survey dilakukan setiap hari kerja\n4. Hasil survey direkap setiap bulan\n5. Hasil evaluasi digunakan untuk bahan\n    pemberian reward and punishment untuk\n    petugas ptsp', '1 item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '8,5', ' -   ', ' Berat '),
(105, 'PANMUD HUKUM', 'Monitoring Pelaksanaan Tugas Posbakum', 'Area 5,6', '1. Melakukan pelaporan setiap bulan\n     kepada Ditjen Badilum terdiri dari\n     Laporan Jumlah, Jenis konsultasi,\n    waktu layanan dan jenis kelamin\n    yang dibantu melalui POSBAKUM\n2. Pelaporan sudah menggunakan\n    aplikasi\n3. Panmud Hukum melakukan monitoring secara \n    berkala terhadap Posbakum untuk memastikan bahwa \n    posbakum melaksanakan tugasnya dan tidak \n    melakukan larangan sebagaimana dalam peraturan \n    Perma No 1 Tahun 2014\n4. Panmud Hukum melakukan evaluasi\n    terhadap kinerja Posbakum setiap\n    tahun', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '8', ' -   ', 'Sedang'),
(106, 'PANMUD HUKUM', 'Posbakum', 'Area 6', '\n1. Adanya MoU antara Ketua Pengadilan\n    dengan Lembaga Layanan Bantuan\n    Hukum dan diperbarui setiap tahun\n2. Absensi Petugas POSBAKUM\n3. Jadwal Piket petugas POSBAKUM\n4. Buku tamu\n5. Daftar pengacara yang dapat\n    dihubungi untuk perkara prodeo\n6. Ada informasi layanan tanpa dipungut\n    biaya yang terpublikasi\n7. Tidak boleh ada identitas OBH pada\n    ruang Posbakum (Spanduk, Banner,\n    Logo)\n8. Kops Surat OBH tidak menggunakan\n    alamat pengadilan', '1 - 2 item pada opsi \"A\" tidak terpenuhi', '3 - 4 item pada opsi \"A\" tidak terpenuhi', '5 - 7 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang'),
(107, 'PANITERA PENGGANTI', 'Mengerjakan minutasi perkara sesuai SOP', 'Area 2', '1. Minutasi selesai maksimal 7 hari untuk perkara pidana \n     dan 14 hari perkara perdata setelah putusan\n2. Tanggal putusan diinput ke SIPP 1 x 24 jam\n    sejak tanggal putusan\n3. Amar putusan diinput ke SIPP 1 x 24 jam sejak\n    tanggal putusan\n4. Mengunggah dokumen putusan ke SIPP 1 x 24\n     jam sejak tanggal putusan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang'),
(108, 'PANITERA PENGGANTI', 'Kewajiban PP untuk membuat berita acara sidang, 1 hari sebelum hari sidang berikutnya, harus sudah selesai dan ditandatangani', 'Area 2,5', '1. Berita Acara Sidang sudah selesai 1 hari\n     sebelum hari sidang berikutnya\n2. Sudah diparaf tiap lembarnya dan BA sudah\n    ditandatangani \n3. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti \n   (dibuktikan dengan data dukung)\n4. Berita Acara sudah diupload kedalam\n   aplikasi SIPP', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(109, 'PANITERA PENGGANTI', 'Penundaan sidang pada SIPP oleh PP', 'Area 2', '1.Penundaan sidang sudah diinput secara\n   lengkap kedalam SIPP\n2. Penginputan kedalam SIPP sudah 1x24 jam\n', '- Penundaan sidang sudah diinput\n   kedalam SIPP tetapi belum lengkap\n- Penginputan kedalam SIPP sudah\n  1x24 jam', '- Penundaan sidang sudah diinput\n   kedalam SIPP tetapi belum lengkap\n- Penginputan kedalam SIPP\n  sebagian lebih dari 1x24 jam', '- Penundaan sidang sudah diinput\n   kedalam SIPP tetapi belum lengkap\n- Penginputan kedalam SIPP lebih\n   dari 1x24 jam', '#NAME?', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(110, 'PANITERA PENGGANTI', 'Kesesuaian SIPP dengan proses yang berlangsung', 'Area 2,5', '1.Pengisian pada SIPP sudah sesuai dengan\n    pemberkasan hardcopynya pada setiap\n    tahapannya (uji petik minimal 10 berkas)\n2. Panmud Pidana telah melakukan monev\n3. Panmud Perdata telah melakukan monev\n4. Hasil Monev sudah ditindaklanjuti', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '8', ' -   ', 'Berat'),
(111, 'JURUSITA/JURUSITA PENGGANTI', 'Permintaan Delegasi Bantuan Panggilan/Pemberitahuan (PN Pengaju)', 'Area 2,5,6', '1.Bukti biaya pengiriman selalu dikirimkan\n    bersamaan dengan permintaan\n2. Data permintaan delegasi diisi lengkap dan\n    tertib pada SIPP\n3. Kelengkapan dokumen selalu diunggah dan\n    dikirimkan melalui SIPP \n4.Memonitor setiap permintaan delegasi keluar dan melaporkan setiap minggu kepada Panitera', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang'),
(112, 'JURUSITA /\nJURUSITA PENGGANTI', 'Pelaksanaan Delegasi Bantuan Panggilan/Pemberitahuan (PN Pelaksana)', 'Area 2,5,6', '1.Jurusita/Jurusita Pengganti mengajukan\n    pencairan anggaran kepada kepada koordinator   \n    delegasi setelah ada Surat Tugas\n2. Jurusita/Jurusita Pengganti menyampaikan\n     relaas kepada Pihak maksimal dua hari sejak surat  \n    tugas diterima\n3. Jurusita/Jurusita Pengganti menyampaikan\n    Relaas pemanggilan/pemberitahuan yang\n   telah dilaksanakan, pada hari yang sama\n   dengan pelaksanaan kepada koordinator\n   delegasi\n4. Jurusita/Jurusita Pengganti selalu memberikan\n    bukti pemanggilan/pemberitahuan kepada\n    Koordinator delegasi sebagai pertanggungjawaban', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang'),
(113, 'JURUSITA / JURUSITA PENGGANTI', 'Pengiriman Bukti Delegasi Pemanggilan/Pemberitahuan yang telah dilaksanakan (PN Pelaksana)', 'Area 2', '1. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti melakukan pemindaian/scanning\n    relaas pemanggilan/pemberitahuan \n2. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti mengunggah ke aplikasi SIPP maksimal \n    pada hari berikutnya setelah penyerahan Relaas\n    dari Jurusita/Jurusita Pengganti\n3. Asli Relaas pemanggilan/pemberitahuan\n    dikirimkan paling lama satu hari setelah\n    koordinator menerima relaas dari Jurusita/\n    Jurusita Pengganti\n4. Koordinator Delegasi/Jurusita/Jurusita\n    Pengganti melakukan pengisian data/\n    informasi termasuk tanggal pelaksanaan, pada \n    aplikasi SIPP', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(114, 'SEKRETARIS', 'Persidangan Elektronik', 'Area 2', '1. Memastikan jaringan internet mendukung pelaksanaan persidangan elektronik\n2.Memastikan ketersediaan sarana prasarana persidangan elektronik sesuai dengan SK Dirjen Nomor 1693/DJU/SK/HM02.3/12/2020\n3.Minimal 1 (satu) ruang persidangan sudah dilengkapi dengan Fasilitas sebagaimana nomor 2\n4.Memastikan sarana prasarana tersebut dalam kondisi baik dan terpelihara ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(115, 'SEKRETARIS', 'Sekretaris melakukan rapat evaluasi kinerja pegawai ', 'Area 3,5', '1. Ada rapat rutin bulanan yang dimulai secara\n     berjenjang dari satuan terkecil (Kasub\n     masing-masing) dibuktikan dengan notulen rapat\n2. Ada monitoring dan evaluasi capaian kinerja berdasarkan PKP/PCK dan LLK\n3. Ada tindak lanjut dari hasil evaluasi\n4. Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(116, 'SEKRETARIS', 'Implementasi RINGKAS 5R', 'Area 1,5', '1.Sudah diterapkan di seluruh bagian (Hakim, Kepaniteraan dan Kesekretariatan)                                                  2.Penataan barang / alat kerja sudah\n   dipisah-pisahkan antara yang jarang\n   dipakai dan sering dipakai\n3. menyingkirkan barang yang tidak\n    diperlukan\n4. Sudah dilakukan monev dan ditindaklanjuti', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '5', ' -   ', 'Ringan'),
(117, 'SEKRETARIS', 'Implementasi RAPI 5R', 'Area 1,5', '1. Sudah diterapkan di seluruh bagian (Hakim, Kepaniteraan dan Kesekretariatan)                                                   2. Penyimpanan barang/ alat sesuai tempat\n    yang telah ditentukan, \n3. Sudah diberi label \n4. Setiap pegawai pada saat datang dan\n    sebelum pulang harus merapikan dan\n    menyimpan berkas kerja ditempat yang\n    telah disediakan\n5. Sudah dilakukan monev dan ditindaklanjuti', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '5', ' -   ', 'Ringan'),
(118, 'SEKRETARIS', 'Implementasi RESIK 5R', 'Area 1,5', '1. Kebersihan pada tempat kerja/lingkungan kerja terjaga\n2. Kebersihan Peralatan kerja terjaga\n3. Sudah diterapkan di seluruh bagian\n4. Sudah dilakukan monev dan ditindaklanjuti', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '5', ' -   ', 'Ringan'),
(119, 'SEKRETARIS', 'Implementasi RAWAT 5R', 'Area 1,5', 'Sudah membakukan/ menetapkan standar untuk mempertahankan 3 R (Rapi,Ringkas,Resik) yaitu dengan menetapkan :\n1. Cara pengendalian, \n2. Mekanisme pemantauan, \n3. Pemeriksaan berkala\n4. Pola tindak lanjut ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '5', ' -   ', 'Ringan'),
(120, 'SEKRETARIS', 'Implementasi RAJIN 5R', 'Area 1,5', '1. Seluruh bagian sudah mengimplementasikan Ringkas dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n2. Seluruh bagian sudah mengimplementasikan Rapi dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n3. Seluruh bagian sudah mengimplementasikan Resik dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n4. Seluruh bagian sudah mengimplementasikan Rawat dan menjadi kebiasaan pribadi tiap SDM (data dukung)\n', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '5', ' -   ', 'Ringan'),
(121, 'SEKRETARIS', 'Sarana dan Prasarana untuk layanan Disabilitas di Pengadilan \nsesuai SK Dirjen No 1692/DJU/SK/PS.00/12/2020', 'Area 6\n', '1. Tersedia Parkir khusus Disabilitas                                                 \n2. Jalur Guiding Block dan warning Block menuju gedung dan ruangan di pengadilan\n3. Ramp/Jalur Landai\n4.Alat bantu mobilitas (kursi roda dan tongkat), alat bantu dengar\n5.Kursi tunggu Disabilitas\n6.Tempat yang disediakan khusus untuk pengguna kursi roda pada pelayanan PTSP, ruang sidang dan layanan publik lainnya \n7. Ruang sidang ramah disabilitas\n8. Ruang kesehatan yang dapat digunakan sebagai ruang bagi penyandang disabilitas Intelektual\n9. Tersedia daftar pendamping/pembimbing, penerjemah dan petugas lain yang terkait \n10. Sudah ada petugas yang mengikuti pelatihan disabilitas\n11.Sudah ada papan informasi visual\n12. Toilet khusus Disabilitas (tinggi toilet, pegangan rambat, tombol darurat)\n13. Sudah ada media informasi braile\n14. Website pengadilan sudah dilengkapi screen reader', '1 - 4 item pada opsi \"A\" tidak terpenuhi', '5 - 8 item pada opsi \"A\" tidak terpenuhi', '9 - 13 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang'),
(122, 'SEKRETARIS', 'Sekretaris melakukan rapat evaluasi anggaran per triwulan dan menyampaikan Laporan Realisasi Anggaran ( LRA ) tiap bulan kepada KPT', 'Area 4,5', '1. Sekretaris melaporkan secara tertulis\n    setiap bulan kepada KPT\n2. Sudah dilakukan secara tertib setiap\n    triwulan                                                                      \n3. Pelaksanaan sudah dimonitoring,\n    evaluasi \n4. Sudah ditindaklanjuti\n5.Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(123, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) membuat laporan persemester dan tahunan terhadap Barang Milik Negara (BMN) ke Badan Urusan Administrasi MA (DIPA 01) dan Badilum (DIPA 03)', 'Area 4,5', '1. Sudah dilakukan secara tertib setiap\n     persemester \n2. Sudah dilakukan secara tertib setiap tahunan\n3. Pelaksanaan sudah dimonitoring, evaluasi\n    dan ditindaklanjuti\n4. Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(124, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) membuat laporan pengawasan dan pengendalian BMN ke Kantor Pelayanan Kekayaan Negara Lelang (KPKNL) ', 'ETARISoen 2', '1.  Sudah dilakukan secara tertib dan berkala\n2. Pelaksanaan sudah dimonitoring, evaluasi \n3. Sudah ditindaklanjuti\n4. Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(125, 'SEKRETARIS', 'Sekretaris selaku Kuasa Pengguna Barang (KPB) mengusulkan penetapan status penggunaan BMN ke Sekretaris MA cq Kepala Biro Perlengkapan', 'Area 4,5', '1. Sudah mengusulkan secara tertulis, tertib\n    dan berkala\n2. Terdokumentasi dengan baik\n3. Sudah dilakukan Monev\n4. Sudah ditindaklanjuti', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(126, 'SEKRETARIS', 'Tugas Document Control/ Pengendalian Dokumen (DC)', 'Area 2', '1. Melakukan penyimpanan arsip hasil\n    kegiatan APM dan ZI (Dokumen tertata dengan\n    baik)\n2. Melakukan pengendalian terhadap\n    kesesuaian dokumen yang beredar\n3. Menjadi pusat data dokumentasi tim APM\n4. Memastikan kecukupan dokumentasi\n    (formulir-formulir APM yang dikeluarkan\n    oleh Ditjen Badilum)\n5. Membuat laporan kepada QMR tentang\n    kegiatan dokumentasi tim APM', '1 item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3-4  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '4', ' -   ', 'Berat'),
(127, 'SEKRETARIS', 'Kelengkapan Document pada Document Control', 'Area 2', 'Kelengkapan dokumen Akreditasi dan Zona Integritas\n1. Dokumen tertata dengan baik \n2. List daftar master dokumen\n3. Bukti Distribusi dokumen\n4. Penomoran dokumen\n5. Penggunaan stamp \"terkendali\", \"tidak\n    terkendali\" dan \"kadaluarsa\"', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(128, 'SEKRETARIS', 'Pengadaan Barang dan Jasa (SK PPK, SK Pejabat Pengadaan dan SK Petugas penyimpan BMN)', 'Area 4,5,6', '1. Seluruh SK sudah ditetapkan dan tepat\n     sesuai Perpres No 16 Tahun 2018\n2. SK sudah diperbaharui setiap tahun\n3. Sudah di Monev\n4. Sudah Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(129, 'SEKRETARIS', 'Tim Pengelola Website', 'Area 2,5,6', '1. Ada SK Tim Pengelola Website yang mengatur\n    Tata Cara pengelolaan website dan ditetapkan\n    oleh Ketua Pengadilan Negeri\n2. Memastikan isi website selalu diperbaharui\n3. Memahami keterbukaan informasi publik\n4. Melakukan monev secara berkala (data\n    dukung)', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', ' Sedang '),
(130, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(131, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Implementasi SOP', 'Area 2,5', '1. SOP telah dibuat sesuai dengan\n    Peraturan Sekretaris Mahkamah Agung\n    R.I Nomor 002 Tahun 2012 tentang\n    Pedoman Penyusunan SOP di\n    Lingkungan MA dan Badan Peradilan\n    yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(132, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pelaksanaan absensi sesuai dengan Perma No. 7 Tahun 2016 dan SK KMA 071/KMA/SK/V/2008 (uji petik tiga bulan terakhir)', 'Area 2,3,5', '1. Absensi manual dan finger print sesuai \n2. pengisian absensi manual sudah sesuai\n    ketentuan\n3. sudah diparaf dan digaris merah oleh petugas\n4. sudah dimonitoring dan dievaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(133, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Izin keluar kantor menggunakan formulir sesuai Perma No. 7 Tahun 2016 dan SK KMA 071/KMA/SK/V/2008 atau surat tugas sesuai ketentuan (uji petik tiga bulan terakhir)', 'Area 2,3,5', '1. Sudah selalu dilaksanakan\n2. Formulir ijin keluar kantor sesuai SK KMA\n3. Surat ijin keluar diketahui pimpinan\n4. Pengarsipan surat ijin keluar tertata dengan\n    rapi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(134, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Peta kekuatan pegawai, rencana kebutuhan pegawai, dan Daftar Urut Kepangkatan', 'Area 3', '1. Sudah ada dan sudah tepat\n2. sudah ada dokumen Peta kekuatan pegawai\n3. terencananya kebutuhan pegawai\n4. Daftar urut kepangkatan diperbaharui\n', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '3,5', ' -   ', 'Sedang'),
(135, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Baperjakat dan penempatan pegawai sudah sesuai dengan kompetensi ', 'Area 2,3', '1. Sudah ada SK tim Baperjakat\n2. Sudah dilaksanakan \n3. Proses pelaksanaan baperjakat sesuai dengan\n    aturan yang berlaku (minimal 6 bulan sekali)\n4. Penempatan pegawai sudah sesuai\n    kompetensi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '3,5', ' -   ', 'Sedang'),
(136, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Analisa pengembangan kompetensi \n', 'Area 3', '1. Sudah melakukan Analisa Pengembangan Kompetensi (Training Need Analysis)\n2. Rencana pengembangan kompetensi pegawai,\n    apakah mempertimbangkan hasil pengelolaan\n    kinerja pegawai\n3. Sudah tersedia data persentase kesenjangan \n    kompetensi pegawai yang ada dengan standar \n   kompetensi yang ditetapkan untuk masing-masing \n   jabatan\n4. Pegawai di Unit Kerja telah memperoleh\n    kesempatan/hak untuk mengikuti diklat\n    maupun pengembangan kompetensi lainnya\n5. unit kerja melakukan upaya pengembangan\n    kompetensi kepada pegawai (dapat melalui\n    pengikutsertaan pada lembaga pelatihan, in\n    house training, atau melalui coaching, atau\n    mentoring, dll)\n6. monitoring dan evaluasi terhadap hasil\n    pengembangan kompetensi dalam kaitannya\n    dengan perbaikan kinerja', ' 1-2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', '5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(137, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Arsip kepegawaian', 'Area 2,3,5', '1. Tersusun secara sistematis sesuai jabatan,\n     lengkap dan rapi\n2. Data kepegawaian diperbarui\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(138, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengelolaan SIKEP', 'Area 3', '1. Data Lengkap (100%)\n2. Data akurat\n3. Data terbarui\n4. Seluruh E doc SK Kepegawaian seluruh\n    pegawai teknis/ non teknis sudah di upload\n    (100%)\n5. Data untuk tanda tangan elektronik lengkap\n    (No HP, NIK, Email domain MA, uploud e_doc\n   KTP dengan format jpg atau jpeg dan berwarna)', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(139, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'RKP, RKGB dan usul pensiun', 'Area 3', '1. RKP seluruhnya sudah dibuat \n     (untuk periode 1 tahun)\n2. RKGB seluruhnya sudah dibuat \n     (untuk periode 1 tahun) \n3. Usul pensiun sudah dibuat dan dikirim ke\n    Kanreg setempat                                      \n4. RKP, RKGB, dan usul pensiun sudah\n    terinformsikan (melalui papan atau monitor) ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(140, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,48', ' -   ', 'Ringan'),
(141, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pemberian sanksi dan penghargaan', 'Area 1,3,6', '1. Sudah dilaksanakan sesuai hasil\n     evaluasi (data dukung SK Pimpinan)                                                              2. Ada Berita Acara\n3. Terdokumentasi dengan baik\n4. Terakomodir dalam sistem promosi dan\n    mutasi internal', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(142, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Sasaran Kerja Pegawai (SKP) dan penilaian prestasi kerja', 'Area 2,3,5', '1. sasaran kerja pegawai telah dibuat          \n2. pengisian SKP sudah sesuai dengan Tusi\n3. penilaian prestasi kerja dilakukan per bulan\n4. sudah diarsipkan dan tertata', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(143, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Prosedur izin (keluar negeri,belajar,tugas belajar dan cuti)', 'Area 3', '1. Sudah dilaksanakan sesuai dengan PP\n    Nomor 11 Tahun 2017, SK KMA 125\n    tahun 2009, perma 7 tahun 2016.\n2. Sudah terdokumentasi dengan baik', '1. Sebagian sudah dilaksanakan\n    sesuai dengan PP Nomor 11 Tahun\n    2017, SK KMA 125 tahun 2009,\n    perma 7 tahun 2016.\n2. Sudah terdokumentasi dengan baik', '1. Sebagian sudah dilaksanakan\n    sesuai dengan PP Nomor 11 Tahun\n    2017, SK KMA 125 tahun 2009,\n    perma 7 tahun 2016.\n2. Belum terdokumentasi dengan baik', '1. Sudah dilaksanakan belum sesuai\n    dengan PP Nomor 11 Tahun 2017,SK\n    KMA 125 tahun 2009, perma 7 tahun\n    2016.\n2. Belum terdokumentasi dengan baik', 'Belum dilaksanakan', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(144, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Penyusunan Keputusan Pimpinan sesuai dengan Peraturan Kepala Arsip Nasional Indonesia No. 2 Tahun 2014 ', 'Area 2', '1. Sudah  sesuai \n2. sudah terdokumentasi \n3. sudah dimonitoring\n4. Sudah dievaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,5', ' -   ', 'Ringan'),
(145, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Dokumentasi Rapat/ Notulen Rapat', 'Area 2', '1. Ditunjuk penanggung jawab notulen oleh\n    Pimpinan satker yang ditetapkan dengan SK                                                2. Setiap rapat sudah dibuatkan notulen \n3. Setiap notulen didokumentasikan menjadi\n    satu kesatuan dengan undangan, foto dan\n    daftar hadir.\n4. Sudah terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(146, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengelolaan tenaga honorer\n', 'Area 2,3', '1. Proses Perekrutan dilaksanakan secara\n    terbuka \n2. Ada kriteria kelulusan yang ditetapkan oleh\n    KPA  dan dituangkan dalam BA                                                  3. SK terdokumentasi dengan baik\n4. Evaluasi minimal 1 kali dalam setahun\n5. Pembiayaan oleh DIPA\n6. Ada kontrak kerja yang ditanda tangani KPA                                               ', ' 1 item pada opsi \"A\" tidak terpenuhi', '2 - 3  item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(147, 'KEPEGAWAIAN, ORGANISASI DAN TATA LAKSANA', 'Pengisian Laporan Lembar kerja (LLK) dan penilaian Kinerja Pegawai (PKP)', 'Area 3', '1. Sudah diisi secara rutin dan menggunakan\n    aplikasi\n2. Sudah diverifikasi oleh atasan langsung\n3. Menjadi salah satu bahan evaluasi kinerja ASN Pengadilan\n4. Terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(148, 'UMUM DAN KEUANGAN', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,5', ' -   ', 'Ringan'),
(149, 'UMUM DAN KEUANGAN', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(150, 'UMUM DAN KEUANGAN', 'Implementasi SOP', 'Area 2,5', '1. SOP telah dibuat sesuai dengan\n     Peraturan Sekretaris Mahkamah Agung\n     R.I Nomor 002 Tahun 2012 tentang\n     Pedoman Penyusunan SOP di\n     Lingkungan MA dan Badan Peradilan\n     yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(151, 'UMUM DAN KEUANGAN', 'SK Pengelola BMN dan Laporan inventaris barang milik negara (SIMAK BMN) ', 'Area 4,5', '1. Sudah ada SK\n2. Sudah dilaksanakan\n3. Sudah dilaporkan\n4. Diupdate \n5. tersedia data dukung', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(152, 'UMUM DAN KEUANGAN', 'Nilai Kapitalisasi Barang Milik Negara (BMN)', 'Area 4,5', '1. Belanja barang peralatan dan mesin\n     diatas Rp.1.000.000,- dengan masa\n     manfaat lebih dari 1 tahun telah\n     menggunakan Akun Belanja Modal.\n2. Belanja barang gedung dan bangunan\n    diatas Rp.25.000.000,- dengan masa\n    manfaat lebih dari 1 tahun telah\n    menggunakan Akun Belanja Modal.\n3. Barang hasil pengadaan telah diinput\n    ke dalam daftar BMN pada aplikasi\n   SIMAK - BMN. ', '1. Belanja barang peralatan dan\n    mesin diatas Rp.1.000.000,-\n    dengan masa manfaat lebih\n    dari 1 tahun belummenggunakan\n    Akun Belanja Modal.\n2. Belanja barang gedung dan\n    bangunan diatas Rp.25.000.000,-\n    dengan masa manfaat lebih dari 1\n    tahun telah menggunakan Akun\n    Belanja Modal.\n3. Barang hasil pengadaan telah\n    diinput ke dalam daftar BMN pada\n    aplikasi SIMAK - BMN. \n', '1. Belanja barang peralatan dan\n     mesin diatas Rp.1.000.000,-\n    dengan masa manfaat lebih dari\n    1 tahun belum menggunakan\n    Akun Belanja Modal.\n2. Belanja barang gedung dan\n    bangunan diatas Rp.25.000.000,-\n    dengan masa manfaat lebih dari 1\n    tahun belum menggunakan Akun\n    Belanja Modal.\n3. Barang hasil pengadaan telah\n    diinput ke dalam daftar BMN pada\n    aplikasi SIMAK - BMN. ', '1. Belanja barang peralatan dan\n     mesin diatas Rp.1.000.000,-\n     dengan masa manfaat lebih dari 1\n     tahun belum menggunakan Akun\n     Belanja Modal.\n2. Belanja barang gedung dan\n    bangunan diatas Rp.25.000.000,-\n    dengan masa manfaat lebih dari 1\n    tahun belum menggunakan Akun\n    Belanja Modal.\n3. Barang hasil pengadaan tidak\n   diinput ke dalam daftar BMN pada\n    aplikasi SIMAK - BMN. ', 'Tidak dilaksanakan seluruhnya', '', 'CUSTOMER FOCUS', '', '8', ' -   ', 'Berat'),
(153, 'UMUM DAN KEUANGAN', 'Pencatatan Aset  lainnya', 'Area 4', '1. Sudah ada SK Tim Penilai Kondisi BMN\n     yang diperbaharui setiap tahun\n2. Laporan dari Tim Penilai kepada KPB\n    setahun sekali\n3. KPB membuat SK Penghentian pemakaian\n4. Register Transaksi Harian (RTH)\n    Penghentian Penggunaan BMN\n5. Usulan Penghapusan BMN', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(154, 'UMUM DAN KEUANGAN', 'Laporan Pengawasan dan Pengendalian (WASDAL) BMN', 'Area 2,5', ' 1. Sudah mengisi aplikasi Sistem Informasi\n     Manajemen Aset Negara (SIMAN)\n 2. Laporan Wasdal BMN sudah ditandatangani\n     oleh KPB setiap tahun\n 3. Laporan sudah dikirim ke KPKNL setempat\n     (sudah ada tanda terima)\n4. Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(155, 'UMUM DAN KEUANGAN', 'Penginputan Aset Tetap', 'Area 2,4,5', '1. Kesesuaian jumlah dan harga barang yang\n    diinput pada SIMAK BMN saat pembelian\n2. Kesesuaian Spesifikasi Barang yang diinput\n3. Pengarsipan Dokumen Pembelian aset tetap\n    sudah tersusun dengan rapi \n4. Sudah di monitoring dan evaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(156, 'UMUM DAN KEUANGAN', 'Penatausahaan Barang Persediaan', 'Area 2,4,5', '1. Kesesuaian jumlah dan harga barang yang\n     diinput pada aplikasi persediaan saat\n     pembelian\n2. Dokumen permintaan barang persediaan\n    dari masing - masing bagian terdokumentasi\n    dengan baik\n3. Dokumen serah terima barang sudah di\n    tandatangani oleh masing - masing pihak\n4. Terdapat kartu pengawasan pengendalian\n     per item barang persediaan\n5. Laporan berita acara opname fisik barang\n    persediaan telah dilakukan per semester', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(157, 'UMUM DAN KEUANGAN', 'Barang Persediaan Dipa 01 dan Dipa 03', 'Area 2,4,5', '1. Data dan Barang Persediaan sesuai \n2. Barang tertata rapi \n3. Penyimpanan terpisah antara Dipa 01\n    dan Dipa 03\n4. Laporan diserahkan ke Sekretaris \n5. Kartu Kendali Pengawasan Barang Persediaan / ATK       ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(158, 'UMUM DAN KEUANGAN', 'Pengelolaan Kendaraan Dinas', 'Area 2,4,5', '1. Penunjukan kendaraan dinas sudah\n    sesuai PMK 76/PMK.06/2015\n2. Penggunaan anggaran kendaraan dinas\n    tidak melebihi standar biaya masukan\n3. Kartu kendali penggunaan kendaraan\n    dinas telah dibuat\n4. Pembayaran pajak STNK telah dibayar\n    dengan tertib', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(159, 'UMUM DAN KEUANGAN', 'Pengelolaan Rumah Dinas', 'Area 2,4,5', '1. Perhitungan sewa rumah dinas telah\n     sesuai dengan keputusan menteri\n     KIMPRASWIL Nomor 373/UPTS/M/2001\n2. Pembayaran PBB rumah dinas telah\n    dibayar dengan tertib \n3. Terdokumentasi dengan baik\n4. Terdapat monitoring dan evaluasi.\n     terhadap Hakim yang mendapat fasilitas\n     rumah dinas dan tunjangan sewa rumah\n     dinas. \n5. Nilai HSBGN (Harga Satuan Bangunan\n    Gedung Negara) per wilayah telah diupdate\n    secara periodik dalam menghitung tarif\n    sewa.', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(160, 'UMUM DAN KEUANGAN', 'SK Penunjukan Penghunian Rumah Dinas', 'Area 4,5', '1. SK ditanda tangani KPB\n2.Tidak ada pemegang ganda Rumah dinas                                                             3. Membayar sewa sesuai peraturan\n    Permen PU No.22/PRT/M/2008\n4. PBB dibayar oleh penghuni\n5.Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(161, 'UMUM DAN KEUANGAN', 'SK Kendaraan Dinas', 'Area 4,5', '1. SK ditanda tangani KPB\n2. Tidak ada pemegang ganda Kendaraan\n    dinas   \n3. Bukti Biaya Pemeliharaan dan\n    Operasional\n4.Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(162, 'UMUM DAN KEUANGAN', 'SK Perangkat IT', 'Area 4,5', '1. SK ditanda tangani KPB\n2. Tidak ada pemegang ganda Perangkat IT                                                             3. Bukti Biaya Pemeliharaan                                             \n4. Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(163, 'UMUM DAN KEUANGAN', 'Pemeliharaan sarana dan prasarana (perangkat IT, rumah dinas, kendaraan dinas, perlengkapan persidangan, kalung hakim dll)', 'Area 4,5', '1. Terpelihara dengan baik\n2. Dirawat secara rutin\n3. Adakartu kontrol\n4. SK BMN sesuai peruntukan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(164, 'UMUM DAN KEUANGAN', 'Perawatan dan Pengelolaan Server', 'Area 2,6', '1. Dirawat secara rutin dan Terpelihara dengan baik \n2. Tersedia Rak Server pada ruang tersendiri\n3. Ada kartu kontrol dan kartu kontrol terisi dengan baik\n4. Tersedia 2 (dua) unit AC yang dinyalakan bergantian', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(165, 'UMUM DAN KEUANGAN', 'Genset', 'Area 4,6', '1. Sudah dilengkapi Genset dan masuk dalam BMN\n2. Kapasitas tersedia sesuai kebutuhan\n3. Dirawat secara rutin dan Terpelihara dengan baik \n4. BBM sudah dianggarkan', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(166, 'UMUM DAN KEUANGAN', 'Daftar barang ruangan & Labelisasi barang milik negara', 'Area 2,4,5', '1. DBR sudah diperbaharui setiap tahun\n2. Sudah dilaporkan pada pimpinan\n3. Seluruh barang BMN sudah Labelisasi \n4. DBR ditandatangani oleh KPB dan\n    Penaggung Jawab ruangan\n5. Nomor inventaris BMN pada Label\n    sesuai dengan SIMAK BMN', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(167, 'UMUM DAN KEUANGAN', 'Layout jalur keluar masuk kendaraan & Pengaturan lahan parkir', 'Area 6', '1. Jalur keluar masuk kendaraan sudah\n   diatur                                                \n2. Tertata dengan baik\n3. Ada petugas parkir \n4. Sudah dipisahkan antara karyawan\n    dengan pengunjung', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '5', ' -   ', 'Ringan'),
(168, 'UMUM DAN KEUANGAN', 'Jalur masuk gedung pengadilan', 'Area 6', '1. Sudah satu pintu\n2. Diawasi oleh CCTV\n3. Dijaga oleh Petugas Keamanan \n4. Diberikan kartu tamu/pengunjung', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '5', ' -   ', 'Ringan'),
(169, 'UMUM DAN KEUANGAN', 'Jalur evakuasi dan titik kumpul', 'Area 6', 'Sudah ada, tepat dan sudah disosialisasikan', 'Sudah ada, kurang tepat dan sudah disosialisasikan', 'Sudah ada, tepat tetapi belum disosialisasikan', 'Sudah ada tetapi belum tepat', 'Belum ada', '', 'CUSTOMER FOCUS', '', '5', ' -   ', 'Ringan'),
(170, 'UMUM DAN KEUANGAN', 'Simulasi tanggap darurat dan kebakaran dengan instansi terkait', 'Area 5,6', '1. Tim penanganan bencana sudah\n    dibentuk\n2. Simulasi sudah dilaksanakan\n3. Diulang setiap tahun\n4. Sudah dimonitoring dan dievaluasi \n   (dibuktikan dengan data dukung) ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '2,25', ' -   ', 'Ringan'),
(171, 'UMUM DAN KEUANGAN', 'Sarana alat pemadam api ringan (APAR)', 'Area 5,6', '1. Tersedia APAR\n2. Penempatan sudah sesuai\n3. APAR tidak kadaluarsa\n4. Terkontrol dengan rutin', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(172, 'UMUM DAN KEUANGAN', 'CCTV', 'Area 5', '1. Tersedia CCTV dengan jumlah yang\n     sesuai\n2. Monitor diruangan KPT\n3. Penempatan sesuai\n4. Perawatan secara rutin (data dukung\n    kartu perawatan)\n5. Kondisi layak/ Tidak ada yang rusak', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '1,5', ' -   ', 'Ringan'),
(173, 'UMUM DAN KEUANGAN', 'Petugas keamanan', 'Area 2,3,6\n', '1. Bersertifikasi\n2. Menggunakan Seragam\n3. Menggunakan peralatan keamanan\n4. Memahami prosedur pengamanan dan\n    evakuasi\n5. 3S (Senyum,Salam,Sapa)', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '5', ' -   ', 'Ringan'),
(174, 'UMUM DAN KEUANGAN', 'Sarana monitoring realisasi anggaran DIPA 01 dan DIPA 03', 'Area 2,5,6', '1. Tersedia sarana publikasi/monitoring\n     realisasi\n2. Terpublikasikan pada Papan Pengumuman\n3. Terpublikasi di Website\n4. Diperbaharui per bulan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(175, 'UMUM DAN KEUANGAN', 'Tersedia informasi tentang : \n1. Visi dan Misi,\n2. Papan daftar nama hakim, \n3. Papan daftar nama mediator, \n4. Alur perkara, \n5. Alur pengajuan dan penanganan layanan\n    bantuan hukum, \n6. Gugatan sederhana, \n7. Informasi panjar biaya perkara, ', 'Area 2,6\n', 'Tersedia seluruhnya\n', '2 item tidak terpenuhi', '4 item tidak terpenuhi', '6 item tidak terpenuhi', 'Belum tersedia', '', 'CUSTOMER FOCUS', '', '5', ' -   ', 'Ringan'),
(176, 'UMUM DAN KEUANGAN', 'Sarana pendukung : \n1. Ruang Posbakum, \n2. Ruang jaksa, \n3. Ruang penasihat hukum, \n4. Ruang Laktasi, \n5. Ruang tunggu pengunjung, \n6. Ruang  kesehatan,\n7. Perpustakaan ', 'Area 6\n', 'Lengkap dan layak\n', '2 item tidak terpenuhi', '4 item tidak terpenuhi', '6 item tidak terpenuhi', 'Tidak lengkap/Tidak ada', '', 'CUSTOMER FOCUS', '', '7', ' -   ', 'Sedang');
INSERT INTO `b` (`no`, `area`, `penilaian`, `area_zi`, `a`, `b`, `c`, `d`, `e`, `nilai_abcde`, `kriteria`, `keterangan`, `bobot_nilai`, `nilai`, `bobot`) VALUES
(177, 'UMUM DAN KEUANGAN', 'Kontrak kantin (PNBP Kantin)', 'Area 4,5', '1. Sudah ada perjanjian sewa\n2. Bukti setoran ke Negara\n3. Perhitungan sewa sudah dilakukan oleh\n    KPKNL\n4. SK Penetapan Pelaksanaan sewa BMN dari \n    Sekretaris MA\n5. Terdokumentasi', '1 item tidak terpenuhi', '2 - 3 item tidak terpenuhi', '4 item tidak terpenuhi', 'Belum dilengkapi', '', 'RESOURCES MANAGEMENT', '', '1,5', ' -   ', 'Ringan'),
(178, 'UMUM DAN KEUANGAN', 'Perjalanan Dinas', 'Area 2,4,5', '1. Pembebanan biaya perjalanan dinas\n     sudah sesuai dengan akun yang\n     tersedia\n2. Perjalanan dinas tersebut\n    menghasilkan output kinerja yang jelas\n3. Waktu dan tempat tujuan sudah sesuai\n    dengan surat tugas\n4. Terdokumentasi dengan baik.', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(179, 'UMUM DAN KEUANGAN', 'Buku-buku keuangan\n1. Buku kas umum (dilengkapi dengan\n    LPJ/akhir bulan)\n2. Buku bank\n3. Buku bantu (Pengawasan kredit, uang\n    persediaan, SPM dan penyetoran pajak\n    PPH Pasal 21, 22 dan 23)', 'Area 2,4,5', '1. Lengkap\n2. Akurat\n3. Bukti sesuai\n4. Sisa uang sama dengan brankas', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '4', ' -   ', 'Berat'),
(180, 'UMUM DAN KEUANGAN', 'SK manajemen pengelolaan keuangan : \n1. SK KPA \n2. SK Pejabat Pembuat Komitmen\n3. SK bendahara pengeluaran/ bendahara\n     pemegang uang muka \n4.  Bendahara penerima, \n5. SK Pembantu Pengelola Keuangan', 'Area 4', 'Lengkap\n', '1 item tidak terpenuhi', '2 item tidak terpenuhi', '4 item tidak terpenuhi', 'Tidak ada\n', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(181, 'UMUM DAN KEUANGAN', 'Dokumen pertanggung jawaban telah disimpan dan diarsipkan', 'Area 2,4,5', '1. Lengkap\n2. Tersusun rapi \n3. Tepat waktu\n4. Tersimpan dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '4', ' -   ', 'Berat'),
(182, 'UMUM DAN KEUANGAN', 'Prosedur Pendistribusian Barang (Berita Acara Serah Terima Barang dan Tanda Terima Barang)', 'Area 2,4,5', '1. Terdata dengan baik\n2. Jumlah sesuai\n3. Tersedia Berita Acara Serah Terima Barang\n4. Tersedia tanda terima', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(183, 'UMUM DAN KEUANGAN', 'Monitoring uang persediaan di brankas bendahara oleh KPA setiap bulan', 'Area 2,4,5', '1. Monitoring sudah dilaksanakan \n2. Berita Acara\n3. Dilaksanakan setiap bulan\n4. Sisa uang di brankas sesuai dengan\n    buku keuangan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(184, 'UMUM DAN KEUANGAN', 'Satker sudah menginput aplikasi monev PP 39 Tahun 2006 dari Bapenas setiap triwulan ', 'Area 2,4,5', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap triwulan\n4. Sudah dilakukan monitoring dan\n    evaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(185, 'UMUM DAN KEUANGAN', 'Satker telah melakukan Rekon internal antara aplikasi SIMAK, BMN, SAIBA dan KOMDANAS setiap bulannya dengan membuat berita acara Rekon internal (mengetahui : operator SAIBA, operator, SIMAK, BMN dan KPA)', 'Area 2,4,5', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap bulan\n4. Tersedia data dukung', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(186, 'UMUM DAN KEUANGAN', 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)', 'Area 2,4,5', '1. KPA telah mengisi dan mengumumkan\n    seluruh paket pengadaan pada aplikasi\n    sirup di awal tahun anggaran', '1. KPA telah mengisi dan\n    mengumumkan sebagian paket\n    pengadaan pada aplikasi SIRUP di\n    awal tahun anggaran', '1. KPA telah mengisi dan\n    mengumumkan sebagian paket\n    pengadaan pada aplikasi SIRUP \n    tetapi tidak pada awal tahun\n    anggaran', '1. KPA belum mengisi dan\n    mengumumkan paket pengadaan\n    pada aplikasi SIRUP', 'Belum ada semua', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(187, 'PERENCANAAN, TI DAN PELAPORAN', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,48', ' -   ', 'Ringan'),
(188, 'PERENCANAAN, TI DAN PELAPORAN', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(189, 'PERENCANAAN, TI DAN PELAPORAN', 'Implementasi SOP', 'Area 2,5', '1. SOP telah dibuat sesuai dengan\n   Peraturan Sekretaris Mahkamah Agung\n   R.I Nomor 002 Tahun 2012 tentang\n   Pedoman Penyusunan SOP di\n   Lingkungan MA dan Badan Peradilan\n   yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(190, 'PERENCANAAN, TI DAN PELAPORAN', 'Satker sudah mengisi aplikasi monev smart setiap bulannya dan melaporkan kepada pimpinan.', 'Area 2,4,5', '1. Indikator kinerja telah mengikuti kaidah\n    SMART\n2. Pengisian data sudah dilakukan\n    secara tertib setiap bulan\n3. Sekretaris melakukan monitoring perbulan\n4. Sudah dievaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(191, 'PERENCANAAN, TI DAN PELAPORAN', 'Penyusunan RKAKL', 'Area 2,4,5', '1. Telah melihatkan pimpinan dan unit lain dalam penyusunan RKAKL\n2. ada instrumen TOR dan RAB \n3. Di input melalui aplikasi SAKTI\n4. sudah dilaksanakan monev', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '5', ' -   ', 'Berat'),
(192, 'PERENCANAAN, TI DAN PELAPORAN', 'Pelaporan Keuangan satker DIPA 01 dan 03  (berdasarkan PMK no.22/PMK.05/2016) sesuai dengan standard akutansi pemerintah yang berlaku. ', 'Area 2,4,5', '1. Adanya Neraca, \n2. Laporan Realisasi Anggaran (LRA), \n3. Laporan Oprasional (LO), \n4. Laporan Perubahan Equitas (LPE) dan \n5. catatan atas laporan keuangan (calk)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '8,5', ' -   ', 'Berat'),
(193, 'PERENCANAAN, TI DAN PELAPORAN', 'Layanan Hukum bagi masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014', 'Area 5,6', '1. Sudah melakukan inovasi untuk mengoptimalkan pelaksanaan layanan hukum pembebasan biaya perkara (prodeo) pada masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014\n2. Sudah melakukan Sosialisasi sesuai SE Dirjen Badilum Nomor 3 Tahun 2020 dan Nomor 2 Tahun 2022 baik secara Internal maupun Eksternal \n3. Pelaporan secara tertib menggunakan aplikasi dari Badilum\n4. Sudah dilaksanakan monev', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '5', ' -   ', 'Berat'),
(194, 'PERENCANAAN, TI DAN PELAPORAN', 'Kepatuhan Backup data sesuai Instruksi Dirjen Badilum Nomor 3102/DJU/SK/HM02.3/9/2019', 'Area 2,5,6', '1. Melakukan backup data minimal\n    1x dalam satu hari\n2. Melakukan singkronisasi ke PT\n    minimal 1x dalam satu hari\n3. Melakukan singkronisasi ke MA\n    minimal 1x dalam satu hari\n4. Melakukan monitoring dan evaluasi\n    terhadap backup data ', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(195, 'PERENCANAAN, TI DAN PELAPORAN', 'Standarisasi website pengadilan (Surat Dirjen Badilum No.362/DJU/HM.02.3/IV/2015\nMenindaklanjuti launching Pedoman Rancangan dan Prinsip Aksebilitas Website Pengadilan oleh Ketua MA-RI pada tanggal 17 Maret 2015)', 'Area 2,6\n', '1. Tampilan website menggunakan template latar\n     belakang merah sesuai ketentuan\n2. Alamat Website menggunakan domain resmi\n    pemerintahan\n3. Web dapat diakses kaum disabilitas\n4. Data selalu terupdate (termasuk profil\n    pengadilan dan berita)\n5. Keterbukaan informasi :\n    - Profil (struktur organisasi,LHKPN,dll)\n    - Pelayanan dasar/standar pelayanan\n      (prosedur beracara,biaya penyelesaian\n      perkara, agenda sidang)\n    - Hak masyarakat (hak bantuan hukum dan\n      biaya perkara cuma-cuma,dll)\n    - Prosedur pengaduan\n    - Ringkasan LKjIP\n    - LRA dan RKAKL\n6. Publikasi IKM, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017 \n7. Publikasi IPAK, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017', '1-2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', '5-6 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '8', ' -   ', 'Berat');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `b`
--
ALTER TABLE `b`
  ADD PRIMARY KEY (`no`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `b`
--
ALTER TABLE `b`
  MODIFY `no` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=196;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
