-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 11, 2022 at 08:47 AM
-- Server version: 5.5.27
-- PHP Version: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `checklist_pn`
--

-- --------------------------------------------------------

--
-- Table structure for table `c`
--

CREATE TABLE `c` (
  `no` int(11) NOT NULL,
  `area` varchar(50) NOT NULL,
  `penilaian` varchar(1000) NOT NULL,
  `area_zi` varchar(1001) NOT NULL,
  `a` varchar(10000) NOT NULL,
  `b` varchar(1000) NOT NULL,
  `c` varchar(1000) NOT NULL,
  `d` varchar(1000) NOT NULL,
  `e` varchar(1000) NOT NULL,
  `nilai_abcde` varchar(25) NOT NULL,
  `kriteria` varchar(50) NOT NULL,
  `keterangan` varchar(500) NOT NULL,
  `bobot_nilai` varchar(50) NOT NULL,
  `nilai` varchar(10) NOT NULL,
  `bobot` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `c`
--

INSERT INTO `checklist` (`no`, `area`, `penilaian`, `area_zi`, `a`, `b`, `c`, `d`, `e`, `nilai_abcde`, `kriteria`, `keterangan`, `bobot_nilai`, `nilai`, `bobot`) VALUES
(1, 'KETUA', 'Manual Mutu :                                                           - Struktur TIM PMPN                                                              - TUSI                                                                                                          - Sasaran Mutu                                                                           - Kebijakan Mutu                                                                                               - Peta Proses Bisnis APM         ', 'Area 6\n', '1. Selalu diperbarui\n2. Sudah disosialisasikan (dibuktikan dengan data dukung berupa \n    notulen)\n3. Manual Mutu sudah diterapkan dengan baik\n    (dibuktikan dengan pelaksanaan asesmen internal 2 kali   \n   setahun, RTM, evaluasi sasaran mutu dll)\n4. Manual mutu dievaluasi minimal setahun sekali dan \n   ditindaklanjuti (dibuktikan dengan data dukung)', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(2, 'KETUA', 'Pelaksanaan Pengawasan dan Pembinaan sesuai dengan PERMA No. 7 Tahun 2016', 'Area 5', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Absensi sudah diterapkan sesuai dengan\n    format Perma No. 7 tahun 2016 baik\n    secara manual maupun Finger print atau \n    elektronik (menyesuaikan dengan sikon)\n3. Surat izin keluar kantor, surat cuti, izin\n    keluar negeri, surat tugas, surat cuti\n    sakit sudah diterapkan sesuai dengan\n    format Perma No. 7 tahun 2016\n4. Sudah dimonitoring & dievaluasi dan\n    ditindaklanjuti', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '    ', '', '8', ''),
(3, 'KETUA', 'Pelaksanaan Pengawasan Melekat dan Pembinaan sesuai dengan PERMA No. 8 Tahun 2016', 'Area 5', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Masing-masing pejabat sudah  \n    melakukan pembinaan dan pengawasan melekat\n3. Sudah dimonitoring dan dievaluasi \n4. Sudah ditindaklanjuti dalam bentuk\n    pemberian sanksi atau penghargaan', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '8', ''),
(4, 'KETUA', 'Pelaksanaan Pengawasan dan Pembinaan sesuai dengan PERMA No. 9 Tahun 2016', 'Area 5\n', '1. Sudah disosialisasikan minimal setahun sekali (dibuktikan \n    dengan data dukung berupa notulen)\n2. Sudah melengkapi sarana pengaduan, antara \n    lain:\n    a. aplikasi SIWAS MA-RI pada situs\n        Mahkamah Agung;\n    b. layanan pesan singkat/SMS;\n    c. surat elektronik (e-mail);\n    d. faksimile;\n    e. telepon;\n    f.  meja Pengaduan;\n    g. form Pengaduan; dan/atau\n    h. kotak Pengaduan.\n3. Sudah dimonitoring dan dievaluasi 1 bulan sekali\n4. Sudah ditindaklanjuti sesuai ketentuan \n    Pasal 6 dan Pasal 7 Perma Nomor 9 \n    Tahun 2016', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '8', ''),
(5, 'KETUA', 'Telah dilaksanakan pembagian tugas antara KPN dengan WKPN serta telah bekerja sama dengan baik', 'Area 2,4', 'Sudah ada SK pembagian tugas, sudah dilaksanakan dan koordinasi berjalan dengan baik sesuai SEMA Nomor 2 Tahun 1988 ', 'Sudah ada SK pembagian tugas tetapi sebagian tugas belum dilaksanakan dan koordinasi berjalan dengan baik', 'Sudah ada SK pembagian tugas tetapi sebagian tugas belum dilaksanakan dan koordinasi berjalan kurang baik', 'Sudah ada SK pembagian tugas tetapi  tugas belum dilaksanakan dan koordinasi tidak baik', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '11', ''),
(6, 'KETUA', 'Pelaksanaan Rapat Evaluasi Kinerja \n', 'Area 4', '1. Rapat rutin secara berkala dimulai\n    secara berjenjang dari satuan terkecil\n    (Kasubbag / Panmud) didampingi Hakim\n    Pengawas Bidang dan dibuktikan\n    dengan notulen rapat\n2. Melakukan evaluasi kinerja minimal 3 bulan sekali\n3. Tindak lanjut hasil evaluasi\n4. Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(7, 'KETUA', '1. Dokumen SAKIP \na.  Indikator Kinerja Utama (IKU) \nb.  Rencana Strategis (RENSTRA) \nc.  Recana Kinerja Tahunan (RKT) \nd.  RENJA - RKAK/L \ne.  Perjanjian Kinerja Tahunan (PKT) \nf.  Laporan Kinerja Instansi Pemerintah\n    (LKjIP) (Pengukuran Kinerja = Realisasi :\n    Target X 100%) \n2. Laporan Tahunan PN yang bersangkutan', 'Area 4', '1. Dokumen Lengkap dan sesuai                                                                                                                                     \n2. Penyusunannya melibatkan seluruh\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP minimal \"BB\"', '1. Dokumen Lengkap dan sesuai                                                                                                                                     \n2. Penyusunannya melibatkan seluruh\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP minimal \"B\"', '1. Dokumen Lengkap dan sesuai                                                                                                                                     \n2. Penyusunannya melibatkan sebagian besar\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP minimal \"B\"', '1. Dokumen Lengkap dan sesuai                                                                                                                                     \n2. Penyusunannya melibatkan sebagian besar\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP belum mencapai \"B\"', '1. Dokumen belum Lengkap dan belum sesuai \n                                                                                                             \n2. Penyusunannya melibatkan sebagian kecil\n    unsur pimpinan dan pegawai\n3. Nilai LKJIP belum mencapai \"B\"', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(8, 'KETUA', 'Indikator Kinerja Utama (IKU) ', 'Area 4', '   IKU telah menggambarkan fungsi utama\n    (core business)  dan telah di reviu\n    Dibuktikan dengan data dukung berupa :\n    a. Dokumen IKU\n    b. Dokumen rapat (undangan, daftar hadir)', '   IKU telah menggambarkan fungsi\n    utama (core business) namun\n    belum di reviu \n   (dibuktikan dengan data dukung)', '   IKU sebagian besar menggambarkan\n    fungsi utama (core business) dan\n    sudah di reviu \n   (dibuktikan dengan data dukung)', '   IKU sebagian kecil menggambarkan\n    fungsi utama (core business) dan\n    sudah di reviu \n   (dibuktikan dengan data dukung)', '  IKU tidak menggambarkan\n   fungsi utama (core business)\n   dan tidak di reviu \n', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(9, 'KETUA', 'Dokumen Rencana Strategis (RENSTRA)', 'Area 4', '1. RENSTRA telah menyajikan Indikator\n     Kinerja Utama (IKU), tujuan dan\n     sasaran organisasi \n2. RENSTRA telah berorientasi pada hasil.\n    (dibuktikan dengan data dukung)', '1. RENSTRA menyajikan sebagian\n    besar Indikator Kinerja Utama\n    (IKU),tujuan dan sasaran organisasi \n2. RENSTRA telah berorientasi pada\n    hasil. (dibuktikan dengan data\n    dukung)', '1. RENSTRA menyajikan sebagian besar Indikator Kinerja Utama (IKU),  tujuan dan sasaran organisasi \n2. RENSTRA belum berorientasi pada hasil. \n(dibuktikan dengan data dukung)', '1. RENSTRA menyajikan sebagian kecil Indikator Kinerja Utama (IKU),  tujuan dan sasaran organisasi \n2. RENSTRA belum berorientasi pada hasil. \n(dibuktikan dengan data dukung)', '1. RENSTRA belum\n     menyajikan sebagian\n     besar Indikator Kinerja\n     Utama (IKU), tujuan dan\n     sasaran organisasi \n2. RENSTRA belum\n    berorientasi pada hasil. \n    (dibuktikan dengan data\n    dukung)', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(10, 'KETUA', 'Dokumen Rencana Kinerja Tahunan (RKT)', 'Area 4', '1. RKT telah sesuai dengan Indikator Kinerja Utama (IKU)\n2. RKT telah digunakan sebagai acuan dalam penyusunan \n   anggaran / RKA dan Perjanjian Kinerja.\n   (dibuktikan dengan data dukung)', '1. RKT telah sesuai dengan Indikator\n     Kinerja Utama (IKU)\n2. RKT telah digunakan sebagai\n    acuan dalam Perjanjian Kinerja\n    namun belum sepenuhnya\n   digunakan sebagai acuan dalam\n   penyusunan anggaran / RKA.\n   (dibuktikan dengan data dukung)', '1. RKT telah sesuai dengan Indikator\n     Kinerja Utama (IKU)\n2. RKT telah digunakan sebagai\n    acuan dalam Perjanjian Kinerja\n    namun belum digunakan sebagai\n    acuan dalam penyusunan\n    anggaran / RKA.\n   (dibuktikan dengan data dukung)', '1. RKT telah sesuai dengan Indikator\n    Kinerja Utama (IKU)\n2. RKT belum digunakan sebagai\n    acuan dalam Perjanjian Kinerja\n    dan penyusunan anggaran / RKA.\n    (dibuktikan dengan data dukung)', '1. RKT tidak sesuai\n     dengan Indikator Kinerja\n     Utama (IKU)\n2. RKT belum digunakan\n    sebagai acuan dalam\n    Perjanjian Kinerja dan\n    penyusunan anggaran /\n    RKA.\n   (dibuktikan dengan data\n   dukung)', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(11, 'KETUA', 'Dokumen Laporan Kinerja Instansi Pemerintah (LKjIP)', 'Area 4', '1. Penyusunan LKjIP  melibatkan seluruh\n    unsur pimpinan \n2. LKjIP telah menyajikan evaluasi dan\n    analisis atas capaian kinerja\n3. LKjIP  telah disampaikan tepat  waktu\n4. LKjIP telah disosialisasikan \n   ', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '', '8,5', ''),
(12, 'KETUA', 'Hasil Monitoring dan Evaluasi LKjIP ', 'Area 4,5', '1. Evaluasi LKJIP melibatkan seluruh\n     unsur pimpinan (data dukung)\n2. Evaluasi LKJIP dilaksanakan pada tahun\n    nilai dikeluarkan\n3. Hasil evaluasi ditindaklanjuti dan dikirimkan\n    ke PT serta disosialisasikan ke seluruh\n    jajaran\n4. Hasil evaluasi dan tindaklanjut\n    terdokumentasi dengan baik ', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '8', ''),
(13, 'KETUA', 'Penetapan Majelis Hakim dan PP', 'Area 2', '1. Penetapan majelis sudah sepenuhnya menggunakan SIPP\n2. Penetapan PP sudah sepenuhnya menggunakan SIPP \n3. Penginputan Penetapan dalam SIPP diinput  1 X 24 jam\n4. Diinput oleh masing-masing pemilik user (Ketua dan Panitera)', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(14, 'KETUA', 'Pengawasan Eksekusi ', 'Area 2,6\n', '1.Seluruh permohonan eksekusi sudah terdata pada \n    SIPP \n2. KPN melakukan monev terhadap pelaksanaan \n    permohonan eksekusi secara manual dan melalui aplikasi \n    PERKUSI setiap bulan dan terdokumentasi dengan baik       \n3. KPN menyurati Pemohon untuk menanyakan \n    kelanjutan proses, jika dalam waktu 30 hari setelah \n    aanmaning tidak ada tindaklanjut dari Pemohon \n    Eksekusi, selanjutnya jika berdasarkan jawaban \n    Pemohon sudah ditindak lanjuti secara sukarela \n    maka diproses sesuai buku pedoman eksekusi \n    Ditjen badilum dan didata ke dalam SIPP, apabila \n    dalam waktu 30 hari pihak tidak menjawab maka atas \n    perintah  KPN, dilakukan penutupan jurnal keuangan eksekusi \n    dan dicatatkan dalam SIPP                           \n4. Seluruh data disetiap tahapan eksekusi yang harus diisi pada \n    SIPP telah terisi 100 % ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '', '7', ''),
(15, 'KETUA', 'Pelaporan Pelaksanaan Eksekusi kepada KPT dalam rangka melaksanakan Surat  WKMA Bidang Yudisial Nomor 59/WK.MA.Y/X/2019 tanggal 30 Oktober 2019 Perihal Eksekusi ', 'Area 2, 5\n', '1. Sudah melaksanakan monitoring dan evaluasi terhadap penyelesaian permohonan eksekusi terutama menyangkut permohonan eksekusi yang belum dilaksanakan (data dukung)\n2. KPN meminta arahan KPT untuk Eksekusi yang \n   tidak dapat dilaksanakan    sesuai Surat  WKMA Bidang Yudisial Nomor 59/WK.MA.Y/X/2019 tanggal 30 Oktober 2019\n3. Sudah melaporkan seluruh permohonan eksekusi (baik yang sudah maupun yang belum dilaksanakan) kepada KPT setiap 6 bulan. \n4. Sudah terdokumentasi dengan baik', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '', '8,5', ''),
(16, 'KETUA', 'Penerapan Restorative Justice ', 'Area 1', '1. Sudah disosialisasikan secara berkala \n2. Melakukan diskusi reguler tentang penerapan RJ di pengadilan yang diikuti oleh seluruh hakim (data dukung)\n3. Sudah melakukan monev secara berkala tentang penerapan RJ \n4.Melaporkan hasil evaluasi penerapan RJ kepada KPT setiap sebulan sekali\n', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(17, 'KETUA', 'Gugatan Sederhana (GS) berdasarkan \nPERMA Nomor 4 Tahun 2019', 'Area 2,5,6', '1. Sudah disosialisasikan ke pihak eksternal melalui berbagai media \n2. Petugas Meja Perdata memahami syarat pendaftaran Gugatan \n    Sederhana\n3. Sudah melakukan monev secara berkala tentang penerapan GS \n4 .Melaporkan hasil evaluasi penerapan GS kepada KPT setiap \n    sebulan sekali', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(18, 'KETUA', 'Monitoring Administrasi Biaya Perkara', 'Area 4,5,6', 'KPN sesuai buku II memerintahkan Panitera secara mendadak untuk  meneliti kebenaran setiap penerimaan dan pengeluaran uang perkara kesesuaian antara pencatatan dibuku jurnal dengan uang yang dibrankas maupun di bank setiap 3 bulan sekali (4x dalam setahun) dan dibuatkan BAP', 'KPN  sesuai buku II memerintahkan Panitera secara mendadak untuk  meneliti kebenaran setiap penerimaan dan pengeluaran uang perkara kesesuaian antara pencatatan dibuku jurnal dengan uang yang dibrankas maupun di bank setiap 3 bulan sekali (3x dalam setahun) dan dibuatkan BAP', 'KPN  sesuai buku II memerintahkan Panitera secara mendadak untuk  meneliti kebenaran setiap penerimaan dan pengeluaran uang perkara kesesuaian antara pencatatan dibuku jurnal dengan uang yang dibrankas maupun di bank setiap 3 bulan sekali (2x dalam setahun) dan dibuatkan BAP', 'KPN  sesuai buku II memerintahkan Panitera secara mendadak untuk  meneliti kebenaran setiap penerimaan dan pengeluaran uang perkara kesesuaian antara pencatatan dibuku jurnal dengan uang yang dibrankas maupun di bank setiap 3 bulan sekali (1x dalam setahun) dan dibuatkan BAP', 'Tidak dilakukan sama sekali\n', '', 'DOCUMENT SYSTEM', '', '', '4', ''),
(19, 'KETUA', 'Kelengkapan SPPA sesuai dengan SK Dirjen Nomor 2176/DJU/SK/PS01/12/2017', 'Area 5,6', 'Kelengkapan SPPA \n1. Ruang tunggu ramah anak korban/saksi,\n2. Ruang tunggu ramah anak pelaku (berteralis)\n3. Ruang sidang anak, \n4. Ruang BaPas/PekSos, \n5. Ruang Diversi/Mediasi,\n6. Ruang Kaukus, \n7. Sarana Teleconfrence.', '1 - 2 item tidak terpenuhi', '3 - 4 item tidak terpenuhi', '5 - 6 item tidak terpenuhi', 'Tidak lengkap\n', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(20, 'KETUA', 'Layanan Disabilitas di Pengadilan \nsesuai SK Dirjen No 1692/DJU/SK/PS.00/12/2020', 'Area 2,6\n', '1. Sudah mensosialisasikan kepada seluruh jajaran pengadilan                                            \n2. Sudah menerapkan Form penilaian personal\n3. Sudah memastikan sarana dan prasarana layanan disabilitas tersedia seluruhnya\n4. Mengadakan MoU dengan Dinas Sosial, Dinas Pendidikan, SLB, organisasi penyandang disabilitas dll\n5. Sudah menerapkan Antrian prioritas pada setiap layanan pengadilan\n6. Sudah membuat SOP untuk layanan pengadilan bagi penyandang disabilitas\n7. sudah melakukan Bimtek Internal untuk layanan disabilitas\n', '1 - 2  item pada opsi \"A\" tidak terpenuhi', ' 3 - 4 item pada opsi \"A\" tidak terpenuhi', '5 - 6 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '7', ''),
(21, 'KETUA', 'Tata tertib persidangan', 'Area 6', '1. Ada SK KPN tentang penunjukkan petugas piket sidang\n2. Petugas piket sidang memahami tugasnya sesuai yang \n    tertuang pada SK KPN\n3. Tata tertib persidangan sudah terinformasikan\n    untuk pengunjung di setiap ruang sidang \n4. Hakim dan Panitera sudah masuk dan keluar\n    dari ruang sidang melalui pintu tersendiri\n5. Sudah dilakukan Monitoring dan evaluasi\n    terhadap tata tertib dan pengamanan\n    persidangan pada setiap rapat bulanan (data\n    dukung notulen rapat dan dokumen lainnya)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', 'Tidak terpenuhi seluruhnya', '', 'CUSTOMER FOCUS', '', '', '7', ''),
(22, 'KETUA', 'Persidangan Elektronik', 'Area 2,6\n', '1. Satker sudah mengadakan bimtek/sosialisasi E-litigasi secara berkala baik ke pihak Eksternal maupun Internal Pengadilan\n2. E-litigasi sudah dilaksanakan minimal 50% dari perkara yang sudah didaftarkan secara ecourt\n3.Monev pelaksanaan persidangan elektronik dengan melakukan diskusi reguler (data dukung)\n4.Pimpinan selalu memberikan arahan (minimal satu tahun sekali) dan memastikan pelaksanaan persidangan secara elektronik berjalan baik dan sesuai ketentuan (notulen)\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(23, 'KETUA', 'Pelaksanaan Pembangunan Zona Integritas', 'Area 1', '1. Internalisasi pembangunan Zona Integritas \n2. Public Campaign pembangunan Zona Integritas\n3. Keterlibatan Pimpinan pada setiap kegiatan pembangunan \n    Zona Integritas\n4. Program perubahan yang diusung Pengadilan \n5. TLHP Internal dan Eksternal 100 %\n6. Nilai IPAK minimal 3,60 \n7. Nilai IKM minimal 3,60 \n8. Terdokumentasi dengan baik', ' 1-2  item pada opsi \"A\" tidak terpenuhi', '3-5 item pada opsi \"A\" tidak terpenuhi', '6-7 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '9', ''),
(24, 'KETUA', 'Pengimplementasian core values ASN  BerAKHLAK (Surat Edaran Menpan RB Nomor 20 Tahun 2021)\na.Berorientasi Pelayanan\nb. Akuntabel\nc. Kompeten\nd.Harmonis\ne. Loyal\nf. Adaptif\ng. Kolaboratif\n', 'Area 1', '1. Sudah disosialisasikan (data dukung)\n2. Setiap unit kerja sudah mengenal core values ASN BerAKHLAK\n    (uji petik)\n3. Sudah melakukan inovasi untuk membudayakan BerAKHLAK\n4. Sudah di Monev (data dukung)\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '', '4,5', ''),
(25, 'KOORDINATOR AREA', 'AREA 1 ZI Manajemen Perubahan \n(Pemenuhan )', 'Area 1', '1. Ada Dokumen rencana aksi/kegiatan dan sudah \n    dimonev\n2. Tim kerja yang dilengkapi dengan Daftar Riwayat \n    Hidup dan Notulen Rapat Pembentukan\n3. Pemantauan/Monitoring dan evaluasi\n    pembangunan WBK/WBBM di setiap area per bulan\n4. Program kerja untuk Perubahan pola\n    pikir dan budaya kerja\n5. SK Penetapan Role Model KPN\n6. SK Penetapan Agen Perubahan', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(26, 'KETUA', 'Penetapan Agen Perubahan (Permenpan Nomor 52 Tahun 2014 dan Permenpan Nomor 27 Tahun 2014)', 'Area 1', '1. Agen Perubahan diusulkan oleh masing-masing pimpinan unit kerja kepada Tim ZI (Area 1) dengan mempertimbangkan kriteria :\n- Berstatus ASN\n- Tidak sedang menjalani Hukuman Disiplin\n- Bertanggung jawab sesuai dengan bidangnya\n- Taat  dan Konsisten terhadap aturan disiplin dan Kode Etik \n   pegawai\n- Mampu memberikan pengaruh positif, inovatif dan proaktif.\n  (dibuktikan dengan pengusulan dari masing-masing unit kerja)\n2. SK Penetapan Agen Perubahan (Perorangan/Tim) yang ditetapkan oleh KPN berdasarkan rekomendasi Area I\n3. Program Perubahan yang diusung harus memenuhi minimal \n   salah satu kriteria :\n- Mendorong peningkatan capaian kinerja utama.\n- Mendorong penguatan integritas serta mengatasi isu strategis, \n- Mendorong peningkatan kualitas layanan bagi pengguna layanan                                             \n4. Rencana tindak Agen Perubahan sesuai dengan lampiran Permenpan Nomor 27 Tahun 2014, Bab III, Tabel I halaman 10 \n5. Monev Tindak Agen Perubahan sesuai dengan lampiran Permenpan Nomor 27 Tahun 2014, Bab III, Tabel II halaman 13 dilakukan oleh Area I dan dilaporkan kepada Pimpinan\n6. Pemilihan dilaksanakan setiap tahun', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '8', ''),
(27, 'KETUA', 'Penetapan Role Model (Permenpan Nomor 52 Tahun 2014)\nPimpinan berperan sebagai role model dalam pembangunan Zona Integritas', 'Area 1', '1. KPN ditetapkan dengan SK KPT sebagai Role Model di \n    Pengadilan Negeri\n2. Selalu diperbarui setiap penggantian pimpinan \n3. KPN sebagai role model sudah mendorong kedisiplinan, prestasi \n    kerja, peningkatan kinerja, pengembangan pola pikir dan budaya \n    kerja di satkernya dengan  program yang terukur\n4.Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '8', ''),
(28, 'KETUA', 'Penandatanganan Pakta Integritas', 'Area 1', '1. Sudah dilaksanakan sesuai PERMENPAN No.\n     52 Tahun 2014 dan Surat Sekma NO.\n     131/1/SEK/KU.01/6/2016\n2. Sudah diperbarui setiap tahun\n3. Pelaksanaannya dilakukan secara resmi\n4. Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '2,25', ''),
(29, 'KOORDINATOR AREA', 'AREA 1 ZI Manajemen Perubahan \n( Reform )', 'Area 1', '1. Agen perubahan telah membuat perubahan yang konkret di Instansi dalam 1 tahun\n(Setiap agen perubahan mempunyai program perubahan)\n2. Perubahan yang dibuat Agen Perubahan telah terintegrasi dalam sistem manajemen ( Seluruh perubahan telah diintegrasikan dalam sistem manajemen )\n3. Pimpinan memiliki komitmen terhadap pelaksanaan reformasi birokrasi, dengan adanya target capaian reformasi yang jelas di dokumen perencanaan\n4. Instansi membangun budaya kerja positif dan menerapkan nilai-nilai organisasi dalam pelaksanaan tugas sehari-hari\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '11', ''),
(30, 'KOORDINATOR AREA', 'AREA 2 ZI Penataan Tatalaksana ( Pemenuhan )', 'Area 2', '1. SOP mengacu pada peta proses bisnis instansi\n2. Prosedur operasional tetap (SOP) telah diterapkan\n3. Prosedur operasional tetap (SOP) telah dievaluasi\n4. Sistem pengukuran kinerja unit sudah menggunakan teknologi informasi\n5. Operasionalisasi manajemen SDM sudah menggunakan teknologi informasi\n6. Pemberian pelayanan kepada publik sudah menggunakan teknologi informasi\n7. Telah dilakukan monitoring dan dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik\n8. Kebijakan tentang  keterbukaan informasi publik telah diterapkan\n9. Telah dilakukan monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik', '1-2  item pada opsi \"A\" tidak terpenuhi', ' 3-5  item pada opsi \"A\" tidak terpenuhi', '6-8   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(31, 'KOORDINATOR AREA', 'AREA 2 ZI Penataan Tatalaksana ( Reform )', 'Area 2', '`1. Telah disusun peta proses bisnis dengan adanya penyederhanaan jabatan\n2. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien\n3. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan internal organisasi yang lebih cepat dan efisien\n4. Transformasi digital pada bidang proses bisnis utama telah mampu memberikan nilai manfaat bagi unit kerja secara optimal \n5. Transformasi digital pada bidang administrasi pemerintahan telah mampu memberikan nilai manfaat bagi unit kerja secara optimal\n6. Transformasi digital pada bidang pelayanan publik telah mampu memberikan nilai manfaat bagi unit kerja secara optimal', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(32, 'KOORDINATOR AREA', 'AREA 3 ZI Penataan SDM ( Pemenuhan )', 'Area 3', '1. Kebutuhan pegawai mengacu kepada peta jabatan dan hasil analisa beban kerja \n2. Penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai \n3. Penempatan pegawai hasil rekrutmen dan mutasi pegawai telah memberikan perbaikan terhadap kinerja unit kerja (data dukung hasil monev)\n4. Telah dilakukan mutasi pegawai antar jabatan dengan memperhatikan kompetensi jabatan dan mengikuti pola mutasi internal\n5. Telah dilakukan Training Need Analysis dan mempertimbangkan hasil pengelolaan kinerja pegawai untuk pengembangan kompetensi \n6. Pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat atau telah diikutsertakan pada lembaga pelatihan, in-house training, coaching, mentoring dan sejenisnya untuk pengembangan kompetensi\n7. Telah dilakukan monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja\n8. Terdapat penetapan kinerja individu yang terkait dengan perjanjian kinerja organisasi\n9. Ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya\n10. Pengukuran kinerja individu dilakukan secara periodik\n11. Hasil penilaian kinerja individu telah dijadikan dasar untuk pemberian reward\n12. Aturan disiplin/kode etik/kode perilaku telah dilaksanakan/diimplementasikan\n13. Data informasi kepegawaian unit kerja telah dimutakhirkan secara berkala', '1-4  item pada opsi \"A\" tidak terpenuhi', ' 5-8  item pada opsi \"A\" tidak terpenuhi', '9-12   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '', '2,55', ''),
(33, 'KOORDINATOR AREA', 'AREA 3 ZI Penataan SDM ( Reform )', 'Area 3', '1. Ukuran kinerja individu telah berorientasi hasil (outcome) \n2. Hasil assemen telah dijadikan pertimbangan untuk mutasi dan pengembangan karir pegawai\n3. Penurunan pelanggaran disiplin pegawai\n(Data dukung berupa monev terhadap:\n- Jumlah pelanggaran tahun sebelumnya\n- Jumlah pelanggaran tahun ini\n- Jumlah pelanggaran yang telah diberikan sanksi/hukuman)\n4.Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '', '2,55', ''),
(34, 'KETUA', 'AREA 4 ZI Penguatan Akuntabilitas \n(Pemenuhan )', 'Area 4', '1. Pimpinan terlibat secara langsung pada saat penyusunan perencanaan dan penyusunan penetapan kinerja\n2. Pimpinan memantau pencapaian kinerja secara berkala\n3. Terdapat sistem informasi/mekanisme informasi kinerja\n4. Unit kerja telah berupaya meningkatkan kapasitas SDM yang menangangi akuntabilitas kinerja', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(35, 'KOORDINATOR AREA', 'AREA 4 ZI Penguatan Akuntabilitas\n (Reform )', 'Area 4', '1. Persentase capaian pada sasaran kinerja 100% atau lebih\n     (Data dukung berupa monev terhadap Jumlah Sasaran Kinerja dan Jumlah \n      Sasaran Kinerja yang tercapai 100% atau lebih)\n2. Hasil Capaian/Monitoring Perjanjian Kinerja telah dijadikan dasar sebagai \n    pemberian reward and punishment bagi organisasi\n3.Terdapat penjenjangan kinerja yang mengacu pada kinerja utama organisasi\n4.Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(36, 'KOORDINATOR AREA', 'AREA 5 Penguatan Pengawasan (Pemenuhan)', 'Area 5', '1.Pengendalian gratifikasi telah dipublikasikan/dikampaanyekan dan telah diimplementasikan\n2.Telah dibangun lingkungan pengendalian\n3.Telah dilakukan penilaian risiko dan kegiatan pengendalian untuk meminimalisir risiko yang telah diidentifikasi dalam suatu manajemen risiko\n4.SPI telah diinformasikan dan dikomunikasikan kepada seluruh pihak terkait\n5.Pengaduan masyarakat telah dikelola dengan baik (diimplementasikan, dimonev dan ditindaklanjuti)\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3-4   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi SeluruhnyaI29', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(37, 'KOORDINATOR AREA', 'Sistem Pengendalian Intern Pemerintah/ SPIP (Manajemen Risiko)', 'Area 5', '1. Telah ditetapkan Tim Manajemen Risiko \n2. Manajemen Risiko disusun sesuai dengan \n   Keputusan Sekma Nomor  475/SEK/SK/VII/2019                         3.Telah menentukan isu internal dan eksternal\n4.Telah dibuat langkah-langkah antisipasi\n   penanganan risiko (identifikasi risiko)\n5. Melakukan analisa dan Pimpinan menentukan \n    level risiko\n6. Sudah dimonitoring, evaluasi dan   \n    ditindaklanjuti. (minimal satu tahun sekali \n    atau setiap ada perubahan)', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(38, 'KOORDINATOR AREA', 'Sistem Pengendalian Intern Pemerintah/ SPIP (Pemantauan Pengendalian Intern/ Monitoring Evaluasi)', 'Area 5', '1. Tim SPIP/Manejemen risiko mendeteksi\n    setiap perubahan intern dan ekstern dalam\n    kegiatan monitoring setiap bulan (data dukung)\n2.Tim SPIP/ Manejemen risiko  memastikan\n    efektivitas pengendalian risiko melalui kegiatan\n    monitoring dan evaluasi setiap tahun sekali\n    (data dukung)\n3. Melakukan kegiatan identifikasi risiko baru,\n    melalui kegiatan monitoring dan evaluasi setiap\n    tahun sekali (data dukung)\n4. Melakukan sosialiasi perubahan SPIP\n    setiap tahunnya', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(39, 'KOORDINATOR AREA', 'Penanganan Benturan Kepentingan (SK Sekma 59A/Sek/SK/11/2014)', 'Area 5', '1. Sudah ada SK Tim dan SK tatacara\n     Penanganan Benturan Kepentingan, \n2. Sudah disosialisasikan/Internalisasi oleh KPN tentang\n     Penanganan Benturan Kepentingan\n3. Sudah dimonitoring, dievaluasi \n4. Sudah ditindaklanjuti\n', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '0,85', ''),
(40, 'KOORDINATOR AREA', 'Pengendalian gratifikasi sesuai dengan Pedoman Pengendalian Gratifikasi dari KPK', 'Area 5', '1. Sudah ada SK Tim Pengendali Gratifikasi\n2. Sudah ada SK tatacara penanganan gratifikasi \n3. Sudah disosialisasikan oleh KPN tentang\n    pengendalian gratifikasi\n4. Sudah dimonitoring, dievaluasi dan\n    ditindaklanjuti', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '0,85', ''),
(41, 'KOORDINATOR AREA', 'AREA 5 Penguatan Pengawasan (Reform)', 'Area 5', '1.Telah dilakukan mekanisme pengendalian aktivitas secara berjenjang\n2. Persentase penanganan pengaduan masyarakat\n(Jumlah pengaduan masyarakat yang harus ditindaklanjuti, jumlah pengaduan masyarakat yang sedang diproses, jumlah pengaduan masyarakat yang  selesai ditindaklanjuti)\n3.Persentase penyampaian LHKPN 100%\n4.Persentase penyampaian LHKASN 100%\n', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi+G29', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(42, 'KETUA', 'Pelaporan E-LHKPN', 'Area 5', '1. Sudah dilaksanakan dengan benar\n2. Sudah dilaksanakan tepat waktu setiap tahun/\n    setiap ada promosi dan mutasi\n3. Seluruh tenaga teknis dan pejabat struktural\n    sudah melaporkan (100%) per maret setiap\n    tahunnya\n4. Tanda terima dari KPK sudah di upload\n    seluruhnya ke aplikasi SIKEP', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi+G29', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '4', ''),
(43, 'KETUA', 'Pelaporan E-LHKASN', 'Area 5', '1. Sudah dilaksanakan tepat waktu :\n     - 1 (satu) bulan setelah pejabat sebagaimana\n       dimaksud tersebut diangkat dalam jabatan,\n       mutasi atau promosi atau;\n     - 1 (satu) bulan setelah berhenti dari jabatan\n       oleh seluruh ASN yang wajib lapor (100%)\n2. Bukti pelaporan dari SIHARKA sudah diunggah   \n    seluruhnya ke aplikasi SIKEP\n3. Bukti pelaporan dari SIHARKA sudah\n    terpublikasikan seluruhnya pada website\n    pengadilan\n4. Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '4', ''),
(44, 'KETUA', 'AREA 6 Peningkatan Kualitas Pelayanan (Pemenuhan)', 'Area 6', '1.Terdapat kebijakan standar pelayanan\n2.Terdapat media pengaduan dan konsultasi pelayanan yang terintegrasi dengan SP4N-Lapor!\n3.Terdapat unit yang mengelola pengaduan dan konsultasi pelayanan\n4.Telah dilakukan evaluasi atas penanganan keluhan/masukan dan konsultasi\n5.Telah membangun database pelayanan yang terintegrasi\n6.Penerapan Pelayanan Prima\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '5', ''),
(45, 'KOORDINATOR AREA', 'Pelayanan Prima', 'Area 6', '1.Telah dilakukan berbagai upaya peningkatan kemampuan dan/atau kompetensi tentang penerapan budaya pelayanan prima\n2.Informasi tentang pelayanan mudah diakses melalui berbagai media\n3.Telah terdapat sistem pemberian penghargaan dan sanksi bagi petugas pemberi pelayanan\n4.Telah terdapat sistem pemberian kompensasi kepada penerima layanan bila layanan tidak sesuai standar\n5.Terdapat sarana layanan terpadu/terintegrasi (PTSP)\n6.Terdapat inovasi pelayanan\n7.Telah dilakukan perbaikan secara terus menerus\n8.Telah menerapkan teknologi informasi dalam memberikan pelayanan', '1-2  item pada opsi \"A\" tidak terpenuhi', ' 3-4  item pada opsi \"A\" tidak terpenuhi', '5-7   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '7', ''),
(46, 'KETUA', 'Maklumat Pelayanan sesuai Permenpan No. 15 Tahun 2014 Tentang Pedoman Standar Pelayanan.', 'Area 6', '1. Maklumat pelayanan sudah\n   dideklarasikan sesuai dengan isi\n   PERMENPAN No.15 Tahun 2014 Tentang\n   Pedoman Standar Pelayanan \n2. Sudah disosialisasikan melalui berbagai\n    media \n3. Penempatan Maklumat Pelayanan di PTSP dan tempat lainnya yang mudah dilihat pengguna layanan\n4. Sudah dimonitoring, dievaluasi,\n    ditindaklanjuti', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '8', ''),
(47, 'KOORDINATOR AREA', 'Standar Pelayanan Pengadilan sesuai SK. KMA No. 026/KMA/SK/II/2012 dan Permenpan Nomor 15 Tahun 2014', 'Area 6', '1. Standar pelayanan yang memuat unsur-\n    unsur  : dasar hukum, persyaratan,\n    prosedur, jangka waktu penyelesaian  \n    layanan,biaya, produk dan pengelolaan \n    pengaduan sudah tepat dan sudah ditetapkan\n2. Standar pelayanan telah dimaklumatkan \n3. Standar pelayanan telah disosialisasikan/ dipublikasikan kepada petugas dan pengguna\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti/diperbaiki.', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '8', ''),
(48, 'KOORDINATOR AREA', 'AREA 6 Peningkatan Kualitas Pelayanan (Reform)', 'Area 6', '1.Inovasi yang mendorong perbaikan pelayanan publik pada:\n-Kesesuaian Persyaratan dan atau\n- Kemudahan Sistem, Mekanisme, dan Prosedur dan atau\n- Kecepatan Waktu Penyelesaian dan atau\n- Kejelasan Biaya/Tarif, Gratis dan atau\n- Kualitas Produk Spesifikasi Jenis Pelayanan dan atau\n- Kompetensi Pelaksana/Web dan atau\n- Perilaku Pelaksana/Web dan atau\n- Kualitas Sarana dan prasarana dan atau\n- Penanganan Pengaduan, Saran dan Masukan\n2.\'Inovasi pada perijinan/pelayanan telah dipermudah, Waktu lebih cepat, Pelayanan Publik yang terpadu, alur lebih pendek/singkat dan terintegrasi dengan aplikasi\n3 Jumlah Penguna layanan terdokumentasi dengan baik\n4.\'Penanganan pengaduan pelayanan dilakukan melalui berbagai kanal/media secara responsive dan bertanggung jawab', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '', '2,55', ''),
(49, 'KETUA', 'Monitoring  SEMA Nomor 1 tahun 2011 tentang Perubahan Surat Edaran Mahkamah Agung No 2 Tahun 2010 tentang Penyampaian Salinan dan Petikan Putusan', 'Area 2,5,6', 'Sudah dilakukan monitoring evaluasi terhadap :\n1. Penyampaian salinan putusan pidana maksimal 14 hari setelah putusan dibacakan\n2.untuk perkara perdata, salinan sudah siap 14 hari setelah putusan dibacakan  \n3. Penyampaian putusan pidana kepada\n    terdakwa, JPU, Rutan/LP\n4. Sudah dilakukan secara berkala setiap bulan\n5. Hasil Monev sudah ditindaklanjuti\n6. Pelaksanaan sudah didokumentasikan\n    dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4-5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '7', ''),
(50, 'KETUA', 'Monitoring Dan Evaluasi SPPT TI', 'Area 2', '1. Melakukan sosialisasi SPPT TI\n2. Melakukan Monitoring \n3. Melakukan Evaluasi dan sudah ditindaklanjuti\n4. Sudah terdokumentasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(51, 'KETUA', 'Pemanfaatan Ruang Tamu Terbuka sesuai  SEMA No. 3 Tahun 2010 dan Surat Edaran Dirjen Badilum No. 1 Tahun 2012', 'Area 5,6\n', '1. Penataan ruang tamu terbuka terlihat\n    oleh umum \n2. Penerimaan tamu terkait penanganan\n    perkara harus dihadiri kedua belah pihak\n3. Penerimaan tamu terkait penanganan\n    perkara harus mengajukan permohonan\n    kepada Pimpinan Pengadilan\n4.Tamu bagi pejabat dan karyawan\n    Pengadilan yang tidak terkait perkara\n    wajib diterima di ruang tamu terbuka', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '', '3,5', ''),
(52, 'WAKIL KETUA', 'Pengawasan Implementasi Aplikasi SMART dan Aplikasi Monev Bappenas (PP 39 Tahun 2006)', 'Area 4, 5', '1. Pengisian tepat waktu per triwulan\n2. Memastikan seluruh komponen pada aplikasi\n    sudah terisi\n3. Sudah mengimplementasikan kedua\n    aplikasi tersebut dengan baik\n4. Melakukan evaluasi terhadap pelaksanaan\n   monitoring implementasi aplikasi (data dukung)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(53, 'WAKIL KETUA', 'Penanggungjawab pengawasan keakuratan dan ketepatan waktu pengisian data pada SIPP sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP serta pengunggahan putusan pada Direktori Putusan MA', 'Area 2,5', '1. Memastikan Panmud dan Kimwasbid melaksanakan pengawasan dan uji petik terhadap data perkara pada SIPP setiap minggu\n2. Melakukan pembinaan dan pengawasan \n   mengenai anonimisasi pada putusan pengadilan  \n   yang dipublikasikan \n3. Melakukan pembinaan dan pengawasan mengenai pengunggahan \n   putusan pada Direktori Putusan\n4. Melaporkan hasil pelaksanaan monev akurasi data SIPP dan pengunggahan putusan pada DirPut setiap 6 (enam) bulan sekali kepada KPT', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(54, 'WAKIL KETUA', 'WKPN sebagai Koordinator Pengawasan', 'Area 5', '1. Hakim pengawas bidang\n     melaksanakan tugas berdasarkan\n     SK dan ST KPN\n2. Sudah ada pedoman pelaksanaan\n    pengawasan bidang.\n3. WKPN sudah melaksanakan fungsinya\n     sebagai Koordinator Pengawasan\n     Hakim Bidang \n4. WKPN sudah membuat rencana dan\n     jadwal pengawasan\n5. Sudah dilakukan monitoring dan\n    evaluasi terhadap hasil pengawasan\n    bidang dan kinerja Hakim Pengawas\n    Bidang setiap bulan sekali\n6. Menindaklanjuti seluruh hasil evaluasi\n    terhadap laporan hasil pengawasan\n    bidang maupun tata cara pelaksanaan/kinerja\n   pengawasan (dengan data dukung)', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '11', ''),
(55, 'WAKIL KETUA', 'Tugas Wakil Ketua Sebagai MR', 'Area 2,5', '1.Sebagai penanggung jawab kegiatan internal\n    assesmen (data dukung notulen rapat dan\n    dokumen RTM)\n2. Memastikan sistem dokumentasi berjalan\n    dengan baik (melakukan monitoring terhadap\n    dokumen secara berkala)\n3. Melakukan evaluasi untuk menjamin dan\n    memastikan mutu dari proses APM (data\n    dukung)\n4. Membuat laporan kepada Ketua Tim APM\n    tentang kinerja tim APM dan kebutuhan\n    apapun untuk dikoreksi/perbaikan (data\n    dukung)', '1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '11', ''),
(56, 'WAKIL KETUA / MR', 'Assesmen internal\n\n', 'Area 5\n', '1. Sudah ada SK Tim Asesmen Internal\n2. Sudah membuat jadwal Assesmen dalam 1 tahun (minimal 2 kali per tahun)\n3.Sudah melaksanakan rapat persiapan\n   pelaksanaan Assesmen Internal\n4. Sudah ada rencana pelaksanaan untuk setiap\n    Assesmen Internal (yang memuat waktu\n    pelaksanaan, bagian yang diassesmen,nama\n    Assesor yang melaksanakan Assesmen)  \n5. Sudah ada daftar/list pertanyaan Assesmen\n    internal\n6. Assesmen Internal sudah dilakukan secara\n    silang\n7.Tindak lanjut hasil temuan sudah\n   dilaksanakan dan sesuai dengan SOP\n8. Tindak lanjut sudah dimonitoring dan evalusi\n    (dibuktikan dengan data dukung)\n9. Setiap pelaksanaan Assesmen Internal selalu\n    diakhiri dengan RTM\n10. Bertanggung jawab terhadap rekaman hasil\n     assesmen internal kepada Document Control\n     untuk dilakukan pengarsipan', '1 s.d 2 item pada opsi \"A\" tidak terpenuhi', '3 s.d 5 item pada opsi \"A\" tidak terpenuhi', '6 s.d 9  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(57, 'HAKIM', 'Hakim Bertanggung Jawab Terhadap Minutasi Perkara', 'Area 2, 5\n', '1. Minutasi Tepat Waktu (14 hari untuk perkara perdata dan 7 hari untuk perkara pidana)\n2. E-doc putusan sudah diunggah ke SIPP\n3. Sudah dimonitoring dan evaluasi\n4. Sudah ditindaklanjuti (LHP, Buku Pengawasan Bidang, dan Notulen Rapat)', '1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '10', ''),
(58, 'HAKIM', 'Kewajiban Hakim untuk memonitor Berita Acara Sidang', 'Area 2, 5\n', '1. Seluruh Berita Acara Sidang sudah\n    diparaf dan ditandatangani\n2. Seluruh Berita Acara Sidang sudah diunggah\n    ke SIPP\n3. Seluruh Berita Acara Sidang sudah\n    digabungkan dan diarsipkan pada berkas\n    perkara\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti \n   (dibuktikan dengan data dukung)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '10', ''),
(59, 'HAKIM', 'Hakim sudah menggunakan SIPP dalam administrasi perkara', 'Area 2,5', '1. Penetapan hari sidang pertama\n    sudah dilaksanakan dengan\n    menggunakan SIPP\n2. Penetapan penahanan sudah\n    dilaksanakan dengan menggunakan\n    SIPP\n3. Perpanjangan Penahanan sudah\n    dilaksanakan dengan menggunakan\n    SIPP\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti  ', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(60, 'HAKIM', 'Hakim Bertanggung Jawab Terhadap Publikasi putusan pada Direktori Putusan dan kewajiban anonimisasi  putusan', 'Area 2,5,6', '1. Selalu memastikan bahwa putusan perkara\n    yang ditangani sudah terpublikasikan pada\n    Direktori Putusan\n2. Memastikan putusan yang wajib anonimisasi\n    dipublikasikan sesuai SK KMA 1-\n    144/KMA/SK/I/2011\n3. Majelis setiap bulannya melakukan monitoring\n    terhadap publikasi seluruh putusannya pada\n    Direktori Putusan \n4. Majelis setiap bulannya melakukan monitoring\n    terhadap anonimisasi putusannya yang\n    dipublikasikan pada Direktori Putusan', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '10', ''),
(61, 'HAKIM', 'Pengawasan Bidang', 'Area 2,5', '1. Melakukan pengawasan setiap minggu \n2. Sudah ada data/keterangan hasil pengawasan pada buku pengawasan bidang yang dibuat oleh hakim terkait\n3.Membuat Laporan Hasil Pengawasan bidang setiap bulan dan format sudah seragam\n4.Sudah memonev tindaklanjut hasil pengawasan', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'LEADERSHIP', '', '', '10', ''),
(62, 'HAKIM ', 'Hakim Pengawas dan Pengamat telah melakukan Pengawasan berkala sesuai aturan ( KUHAP dan SEMA No. 7 Tahun 1985) dan telah membuat laporan hasil pengawasan dan setiap laporan pengawasan sudah dievaluasi serta ditindaklanjuti, telah dilaporkan kepada Pengadilan Tingkat Banding', 'Area 2,5', '1. Sudah ada SK penunjukkan Hakim\n     Pengawas dan Pengamat\n2. Sudah ada jadwal pengawasan\n3. Ada bukti laporan pengawasan\n4. Sudah dimonitoring, evaluasi dan\n    ditindaklanjuti ', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '7', ''),
(63, 'HAKIM', 'Hakim wajib membuat penetapan penundaan sidang secara tertulis apabila jaksa penuntut umum tidak hadir di persidangan', 'Area 2,5', '1. Selalu dilaksanakan dengan penetapan \n2.  Sudah dimonitoring\n3. Sudah dievaluasi\n4. Sudah ditindaklanjuti  \n    (dibuktikan dengan data dukung)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '8', '');
INSERT INTO `c` (`no`, `area`, `penilaian`, `area_zi`, `a`, `b`, `c`, `d`, `e`, `nilai_abcde`, `kriteria`, `keterangan`, `bobot_nilai`, `nilai`, `bobot`) VALUES
(64, 'HAKIM', 'Court Calender', 'Area 2', '1. Untuk perkara perdata court calender sudah \n    ditandatangani oleh para pihak\n2. Untuk perkara perdata sudah dibuat setelah \n    mediasi gagal \n3. Untuk perkara pidana court calender sudah \n    ditandantangani Hakim, Jaksa, Penasihat Hukum/\n    Terdakwa\n4. Untuk perkara Pidana dibuat sejak sidang \n    pertama.\n5. Court Calender yang sudah ditandatangani sudah  \n   diupload di SIPP untuk selanjutnya diarsipkan di \n   berkas', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 - 4  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '8', ''),
(65, 'PANITERA', 'Pelaksanaan Delegasi berdasarkan SEMA Nomor 6 tahun 2014 tentang Penanganan Pemberitahuan /Panggilan dan Surat Edaran Dirjen Nomor 5 tahun 2019 tentang Peningkatan Kepatuhan Penanganan Bantuan Panggilan/Pemberitahuan Pada Pengadilan Negeri Pengaju', 'Area 2, 5, 6\n', '1. Seluruh permintaan delegasi melalui SIPP\n2. Seluruh tahapan pada kolom delegasi SIPP\n    terinput secara tertib\n3. Bukti pembayaran dikirimkan bersamaan\n    surat permintaan Delegasi\n4. Monev dilakukan secara berkala setiap bulan dan \n    ditindaklanjuti\n5. Terhadap setiap permintaan bantuan yang belum \n    dilaksanakan oleh PN Pelaksana lebih dari 14 hari \n    maka PN wajib menyurati dengan tembusan kepada \n    KPT jika sudah menyurati dua kali belum juga ada \n    tindaklanjut dari PN Pelaksana maka disurati kembali \n    untuk yang ke tiga kali dengan tembusan kepada \n    Badan Pengawasan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(66, 'PANITERA', 'Pelaksanaan Delegasi berdasarkan SEMA Nomor 6 tahun 2014 tentang Penanganan Pemberitahuan /Panggilan dan Surat Edaran Dirjen Nomor 5 tahun 2019 tentang Peningkatan Kepatuhan Penanganan Bantuan Panggilan/Pemberitahuan Pada Pengadilan Negeri Pelaksana', 'Area 2, 5, 6\n', '1. Seluruh tahapan pada kolom delegasi SIPP\n     terinput secara tertib\n2. Seluruh pelaksanaan delegasi Panggilan atau\n    pemberitahuan tidak melampaui 14 hari\n3. Dokumen relaas diupload ke SIPP maksimal 1 hari \n    setelah pelaksanaan relaas\n4. Dokumen fisik dikirimkan ke PN Pengaju\n    paling lambat pada hari berikutnya setelah\n    pengiriman dokumen secara elektronik\n5. Monev dilakukan secara berkala setiap bulan\n6. Hasil Monev sudah ditindaklanjuti\n7. Pelaksanaan sudah didokumentasikan\n    dengan baik', '1-2  item pada opsi \"A\" tidak terpenuhi', ' 3 - 4 item pada opsi \"A\" tidak terpenuhi', '5 - 6 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '', '8', ''),
(67, 'PANITERA', 'Pelaksanaan Rapat evaluasi kinerja pada Kepaniteraan', 'Area 2, 5', '1. Ada rapat rutin bulanan yang dimulai secara\n     berjenjang dari satuan terkecil (Panmud\n     masing-masing) didampingi Hakim Pengawas\n     Bidang dan dibuktikan dengan notulen rapat\n2. Ada monitoring dan evaluasi capaian kinerja,  \n    pencatatan keuangan perkara dan kedisiplinan \n    pengisian data pada SIPP setiap bulan\n3. Ada tindak lanjut dari hasil evaluasi\n4. Terdokumentasi dengan baik', '1  item pada opsi \"A\" tidak terpenuhi', ' 2  item pada opsi \"A\" tidak terpenuhi', '3   item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(68, 'PANITERA', 'Panjar Biaya Perkara \n(Surat Dirjen Badilum Nomor 613/DJU/PS.01/6/2020 tentang Pedoman kepatuhan pemberitahuan pengembalian sisa panjar biaya perkara)', 'Area 2, 5, 6\n', '1. Panitera memastikan bahwa surat pengembalian sisa panjar kepada pihak sudah dikirimkan maksimal 5 (lima) hari kerja setelah tanggal minutasi\n2. Panitera memastikan bahwa seluruh sisa panjar biaya perkara yang sudah diberitahukan kepada pihak, sudah dikembalikan dalam jangka waktu 6 (enam) bulan terhitung sejak tanggal surat pemberitahuan\n3.Seluruh sisa panjar perkara yang sudah melewati 6 (enam) bulan dan tidak diambil pihak setelah diberitahukan harus segera disetorkan ke Kas Negara\n4.Panitera memastikan Panmud Perdata melakukan Monev pengembalian sisa panjar biaya perkara secara berkala dan melaporkan kepada panitera setiap bulannya', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(69, 'PANMUD PIDANA', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '1,48', ''),
(70, 'PANMUD PIDANA', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '2,8', ''),
(71, 'PANMUD PIDANA', 'Implementasi SOP', 'Area 2,5', '1. KPN sudah menetapkan SK tentang\n    pemberlakuan SOP yang dikeluarkan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(72, 'PANMUD PIDANA', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud pidana sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', 'Area 2,5', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(73, 'PANMUD PIDANA', 'Penomoran perkara dan template putusan sudah sesuai dengan SK KMA No. 44 Tahun 2014', 'Area 2,5\n', '1. Penomoran perkara sudah sesuai dengan SK\n     KMA No. 44 Tahun 2014\n2. Template putusan sudah sesuai dengan SK\n    KMA No. 44 Tahun 2014\n3. Template putusan sudah menggunakan SIPP\n4. Sudah dimonev (misal : objek pemeriksaan pengawasan bidang)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '4', ''),
(74, 'PANMUD PIDANA', 'Penyerahan berkas perkara inactive dari Panmud Pidana kepada Panmud Hukum harus dengan Berita Acara Serah Terima Berkas ( dalam jangka waktu 3 hari setelah BHT )\n', 'Area 2', '1. Selalu dilaksanakan\n2. Dilaksanakan tepat waktu\n3. Sudah menggunakan Berita Acara\n4. Sudah diarsipkan dan diinput dalam SIPP', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(75, 'PANMUD PIDANA', 'Pemberkasan Arsip Perkara yang telah diminutasi sudah sesuai dengan SK Direktur Jenderal Badan Peradilan Umum No. 1939/DJU/SK/HM.02.3/10/2018', 'Area 2,5', '1. Susunan Berkas Perkara sudah tepat\n2. Penjilidan Sudah sesuai ketentuan (warna\n    sampul, checklist, dijahit sesuai ketentuan,\n    dan menggunakan laks)\n3. Format Checklist sudah tepat\n4. Format Court Calender sudah tepat\n5. Sudah dilakukan monitoring dan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 - 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '2,8', ''),
(76, 'PANMUD PIDANA', 'Penggunaan Dokumen Elektronik untuk pengajuan upaya hukum Kasasi dan PK sesuai SEMA No 1 Tahun 2014', 'Area 2,5', '1. Seluruh pengajuan upaya hukum Kasasi dan PK sudah \n     melalui Direktori Putusan \n2. KPN sudah membuat SOP Upaya Hukum Kasasi dan\n   PK dengan Dokumen Elektronik\n3. Dokumen Elektronik yang dikirimkan sudah lengkap \n    (uji petik) \n4. Sudah dimonev', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(77, 'PANMUD PIDANA', 'Kelengkapan Berkas Banding', 'Area 2,5', '1. Berkas yang dikirim ke PT sudah lengkap\n     sesuai dengan ketentuan Buku II \n2. Maksimal 14 hari berkas sudah diterima\n    Pengadilan Tinggi (236 KUHAP)\n3. Terdata dalam SIPP \n4. Sudah dimonev                                                                                               ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(78, 'PANMUD PIDANA', 'Kelengkapan Berkas Kasasi (Manual)', 'Area 2', '1. Berkas yang dikirim ke Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Untuk laporan kasasi, penahanan maksimum\n    3 hari sejak adanya permohonan kasasi,\n    harus sudah dilaporkan ke Mahkamah Agung\n3. Berkas perkara permohonan kasasi (ditahan)\n    paling lambat 3 hari setelah memori kasasi\n    diterima, dikirimkan ke Mahkamah Agung\n4. Berkas perkara permohonan kasasi (tidak\n    ditahan ) paling lambat 30 hari setelah memori\n    kasasi diterima, dikirimkan ke Mahkamah\n    Agung\n5. Ceklis kelengkapan berkas kasasi \n6. Penginputan kedalam aplikasi SIPP dilakukan\n   1x24 jam\n\n', '1  item pada opsi \"A\" tidak terpenuhi', ' 2 - 3 item pada opsi \"A\" tidak terpenuhi', '4 - 5 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(79, 'PANMUD PIDANA', 'Kelengkapan Berkas PK (Manual)', 'Area 2', '1. Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II \n2. Kepatuhan waktu dalam pengiriman berkas\n    peninjuan kembali ke Mahkamah Agung\n    dalam waktu maksimal 30 hari setelah\n    Pemeriksaan Persidangan (PIDANA) \n3. Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas PK', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(80, 'PANMUD PIDANA', 'Permohonan kasasi yang telah memenuhi syarat formal selambat lambatnya dalam waktu 14 hari setelah tenggang waktu mengajukan memori kasasi berakhir, berkas kasasi harus sudah dikirim ke Mahkamah Agung (Buku II)', 'Area 2', 'Berkas sudah dikirim tepat waktu dan lengkap ke Mahkamah Agung', 'Berkas dikirim tidak tepat waktu dan susunan berkas lengkap ke Mahkamah Agung', 'Berkas sudah dikirim tepat waktu tetapi tidak lengkap ke Mahkamah Agung', 'Berkas dikirim tidak tepat waktu dan tidak lengkap ke Mahkamah Agung', 'Tidak dilaksanakan', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(81, 'PANMUD PIDANA', 'Kepatuhan PN dalam pelaksanaan :\n1. SEMA 1 Tahun 1987 tentang pengiriman berkas perkara pidana yang terdakwanya berada dalam tahanan\n2. SEMA 3 Tahun 1987 tentang permohonan penetapan penahanan oleh MA bagi terdakwa yang berada dalam tahanan\n3. SEMA 2 Tahun 1998 tentang permohonan kasasi perkara pidana yang terdakwanya berada dalam status tahanan\n4. Surat Panitera MA Nomor 2304/PAN/HK.01/12/2020 tentang Prosedur penyampaian laporan kasasi dan berkas perkara pidana yang Terdakwanya berada dalam status tahanan', 'Area 2', '1. Membuat laporan kasasi perkara pidana yang \n    terdakwanya berada dalam tahanan dengan tepat\n    waktu yakni 3 (hari) kerja terhitung sejak diterimanya \n    permohonan kasasi dari Terdakwa/Jaksa Penuntut \n    Umum\n2. Laporan tersebut disampaikan melalui aplikasi \n    Direktori Putusan MA jika Direktori Putusan MA sedang \n    bermasalah maka dapat melalui email ke   \n   kepaniteraan@mahkamahagung.go.id dan \n   kepaniteraan.mari@gmail.com\n3. Berkas kasasi (Bundel A dan B) perkara pidana yang \n   terdakwanya berada dalam tahanan telah diterima oleh  \n   Mahkamah Agung paling lama 30 (tiga puluh) hari \n   kalender terhitung sejak diajukannya permohonan \n   kasasi\n4. Penyampaian laporan kasasi menggunakan format \n   yang ditentukan dalam SEMA Nomor 2 Tahun 1998\n5. Memberikan \'tanda\' tahanan pada sampul berkas kasasi \n   yang menunjukan bahwa terdakwanya ditahan\n', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(82, 'PANMUD PERDATA', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '1,48', ''),
(83, 'PANMUD PERDATA', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '2,8', ''),
(84, 'PANMUD PERDATA', 'Implementasi SOP', 'Area 2,5', '1. SOP yang dikeluarkan sudah disosialisasikan\n    oleh Dirjen Badilum\n2. Sudah dilaksanakan (uji petik\n    minimal 5 kegiatan) \n3. Sudah dilakukan monitoring dan evaluasi\n4. Sudah melaporkan hasil monev kepada Ditjen\n    Badilum minimal satu tahun sekali', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(85, 'PANMUD PERDATA', 'Pelaksanaan monitoring/pengawasan, evaluasi terhadap keakuratan dan ketepatan waktu pengisian data pada SIPP dan Tindak lanjut hasil pengawasan pada panmud Perdata sesuai Surat Dirjen Badilum No.352/DJU/HM.02.3/3/2021 tentang Akurasi dan Pengendalian Mutu Data SIPP', 'Area 2,5', '1. Dilakukan 1x setiap minggu\n2.  Melaporkan setiap bulan kepada KPN setelah divalidasi oleh panitera\n3. Menindaklanjuti hasil monev yang dilakukan panmud dan seluruh temuan dari pengawasan bidang\n4. Terdokumentasi/tercatat', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(86, 'PANMUD PERDATA', 'Pemberkasan Arsip Perkara yang telah diminutasi sudah sesuai dengan SK Direktur Jenderal Badan Peradilan Umum No. 1939/DJU/SK/HM.02.3/10/2018', 'Area 2,5', '1. Susunan Berkas Perkara sudah tepat\n2. Penjilidan Sudah sesuai ketentuan (warna\n    sampul, checklist, dijahit sesuai ketentuan,\n    dan menggunakan laks)\n3. Format Checklist sudah tepat\n4. Format Court Calender sudah tepat\n5. Sudah dilakukan monitoring dan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 - 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '2,8', ''),
(87, 'PANMUD PERDATA', 'Penomoran perkara dan template putusan sudah sesuai dengan SK KMA No. 44 Tahun 2014', 'Area 2,5\n', '1. Penomoran perkara sudah sesuai dengan SK\n     KMA No. 44 Tahun 2014\n2. Template putusan sudah sesuai dengan SK\n    KMA No. 44 Tahun 2014\n3. Template putusan sudah menggunakan SIPP\n4. Sudah dimonev (misal : objek pemeriksaan pengawasan bidang)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '', '4', ''),
(88, 'PANMUD PERDATA', 'Penyerahan berkas perkara inactive dari Panmud Perdata kepada Panmud Hukum harus dengan Berita Acara Serah Terima Berkas ( dalam jangka waktu 3 hari setelah BHT )', 'Area 2', '1. Selalu dilaksanakan tepat waktu 3 hari\n    setelah BHT\n2. Sudah menggunakan Berita Acara\n3. Sudah diarsipkan\n4. Sudah diinput dalam SIPP dengan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '2,3', ''),
(89, 'PANMUD PERDATA', 'Pelaporan Keuangan Perkara dan Komdanas', 'Area 4,5', '1. Sudah menggunakan aplikasi pelaporan Keuangan Perkara serta Penginputan data  pada aplikasi komdanas secara tepat dan tertib setiap bulan\n2. Pelaporan dilakukan mulai dari tanggal 1 sd  5 setiap bulannya (SEMA Nomor 4 Tahun 2018)\n3. Pengiriman dokumen lengkap sesuai aturan\n4. Pimpinan melakukan monitoring dan evaluasi per bulan\n5. Penutupan register sudah dilakukan secara tertib dan ditandatangani \n', '1 item pada opsi \"A\" tidak terpenuhi', '2-3 item pada opsi \"A\" tidak terpenuhi', '4  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(90, 'PANMUD PERDATA', 'Surat Kuasa Untuk Membayar (SKUM)', 'Area 2', '1. Perhitungan panjar sudah dilakukan secara\n     otomatis\n2. SKUM sudah diberi Nomor (bukan nomor\n    perkara)\n3. Pembayaran melalui Bank / multi chanel\n4. Terdokumentasi dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(91, 'PANMUD PERDATA', 'Penggunaan Dokumen Elektronik untuk pengajuan upaya hukum Kasasi dan PK sesuai SEMA No 1 Tahun 2014', 'Area 2,5', '1. Seluruh pengajuan upaya hukum Kasasi dan PK sudah \n     melalui Direktori Putusan \n2. KPN sudah membuat SOP Upaya Hukum Kasasi dan\n   PK dengan Dokumen Elektronik\n3. Dokumen Elektronik yang dikirimkan sudah lengkap \n    (uji petik) \n4. Sudah dimonev', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(92, 'PANMUD PERDATA', 'Kelengkapan Berkas Banding', 'Area 2', '1. Berkas yang dikirim ke PT sudah lengkap\n     sesuai dengan ketentuan Buku II \n2. Maksimal 14 hari berkas sudah diterima\n    Pengadilan Tinggi   \n3. Terinput dalam SIPP \n4. Terdokumentasi dengan baik                                                                                               ', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', ''),
(93, 'PANMUD PERDATA', 'Kelengkapan Berkas Kasasi (Manual)', 'Area 2', '1. Permohonan kasasi yang telah memenuhi\n     syarat formal selambat lambatnya dalam\n     waktu 14 hari setelah tenggang waktu\n     mengajukan memori kasasi berakhir, berkas\n     kasasi harus sudah dikirim ke Mahkamah Agung\n2.  Berkas yang diterima Mahkamah Agung\n     sudah lengkap sesuai dengan ketentuan\n     Buku II dan SEMA 1 Tahun 2014 (termasuk \n     dokumen elektronik)\n3.Penginputan ke dalam aplikasi SIPP\n    dilakukan 1x24 jam\n4. Ceklis kelengkapan berkas Kasasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '', '3,5', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `c`
--
ALTER TABLE `c`
  ADD PRIMARY KEY (`no`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `c`
--
ALTER TABLE `c`
  MODIFY `no` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

INSERT INTO `checklist` (`no`, `area`, `penilaian`, `area_zi`, `a`, `b`, `c`, `d`, `e`, `nilai_abcde`, `kriteria`, `keterangan`, `bobot`, `nilai`, `ket_bobot`) VALUES
(177, 'UMUM DAN KEUANGAN', 'Kontrak kantin (PNBP Kantin)', 'Area 4,5', '1. Sudah ada perjanjian sewa\n2. Bukti setoran ke Negara\n3. Perhitungan sewa sudah dilakukan oleh\n    KPKNL\n4. SK Penetapan Pelaksanaan sewa BMN dari \n    Sekretaris MA\n5. Terdokumentasi', '1 item tidak terpenuhi', '2 - 3 item tidak terpenuhi', '4 item tidak terpenuhi', 'Belum dilengkapi', '', 'RESOURCES MANAGEMENT', '', '1,5', ' -   ', 'Ringan'),
(178, 'UMUM DAN KEUANGAN', 'Perjalanan Dinas', 'Area 2,4,5', '1. Pembebanan biaya perjalanan dinas\n     sudah sesuai dengan akun yang\n     tersedia\n2. Perjalanan dinas tersebut\n    menghasilkan output kinerja yang jelas\n3. Waktu dan tempat tujuan sudah sesuai\n    dengan surat tugas\n4. Terdokumentasi dengan baik.', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(179, 'UMUM DAN KEUANGAN', 'Buku-buku keuangan\n1. Buku kas umum (dilengkapi dengan\n    LPJ/akhir bulan)\n2. Buku bank\n3. Buku bantu (Pengawasan kredit, uang\n    persediaan, SPM dan penyetoran pajak\n    PPH Pasal 21, 22 dan 23)', 'Area 2,4,5', '1. Lengkap\n2. Akurat\n3. Bukti sesuai\n4. Sisa uang sama dengan brankas', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '4', ' -   ', 'Berat'),
(180, 'UMUM DAN KEUANGAN', 'SK manajemen pengelolaan keuangan : \n1. SK KPA \n2. SK Pejabat Pembuat Komitmen\n3. SK bendahara pengeluaran/ bendahara\n     pemegang uang muka \n4.  Bendahara penerima, \n5. SK Pembantu Pengelola Keuangan', 'Area 4', 'Lengkap\n', '1 item tidak terpenuhi', '2 item tidak terpenuhi', '4 item tidak terpenuhi', 'Tidak ada\n', '', 'RESOURCES MANAGEMENT', '', '4,5', ' -   ', 'Berat'),
(181, 'UMUM DAN KEUANGAN', 'Dokumen pertanggung jawaban telah disimpan dan diarsipkan', 'Area 2,4,5', '1. Lengkap\n2. Tersusun rapi \n3. Tepat waktu\n4. Tersimpan dengan baik', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '4', ' -   ', 'Berat'),
(182, 'UMUM DAN KEUANGAN', 'Prosedur Pendistribusian Barang (Berita Acara Serah Terima Barang dan Tanda Terima Barang)', 'Area 2,4,5', '1. Terdata dengan baik\n2. Jumlah sesuai\n3. Tersedia Berita Acara Serah Terima Barang\n4. Tersedia tanda terima', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'RESOURCES MANAGEMENT', '', '2,55', ' -   ', 'Sedang'),
(183, 'UMUM DAN KEUANGAN', 'Monitoring uang persediaan di brankas bendahara oleh KPA setiap bulan', 'Area 2,4,5', '1. Monitoring sudah dilaksanakan \n2. Berita Acara\n3. Dilaksanakan setiap bulan\n4. Sisa uang di brankas sesuai dengan\n    buku keuangan', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(184, 'UMUM DAN KEUANGAN', 'Satker sudah menginput aplikasi monev PP 39 Tahun 2006 dari Bapenas setiap triwulan ', 'Area 2,4,5', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap triwulan\n4. Sudah dilakukan monitoring dan\n    evaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(185, 'UMUM DAN KEUANGAN', 'Satker telah melakukan Rekon internal antara aplikasi SIMAK, BMN, SAIBA dan KOMDANAS setiap bulannya dengan membuat berita acara Rekon internal (mengetahui : operator SAIBA, operator, SIMAK, BMN dan KPA)', 'Area 2,4,5', '1. Sudah dilaksanakan\n2. Sudah dilaporkan pada pimpinan\n3. Diupdate setiap bulan\n4. Tersedia data dukung', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(186, 'UMUM DAN KEUANGAN', 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)', 'Area 2,4,5', '1. KPA telah mengisi dan mengumumkan\n    seluruh paket pengadaan pada aplikasi\n    sirup di awal tahun anggaran', '1. KPA telah mengisi dan\n    mengumumkan sebagian paket\n    pengadaan pada aplikasi SIRUP di\n    awal tahun anggaran', '1. KPA telah mengisi dan\n    mengumumkan sebagian paket\n    pengadaan pada aplikasi SIRUP \n    tetapi tidak pada awal tahun\n    anggaran', '1. KPA belum mengisi dan\n    mengumumkan paket pengadaan\n    pada aplikasi SIRUP', 'Belum ada semua', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(187, 'PERENCANAAN, TI DAN PELAPORAN', 'Pencatatan surat masuk/keluar', 'Area 2', '1. Sudah tercatat\n2. Sudah terkendali \n3. Sudah menggunakan aplikasi\n4. Sudah didistribusikan tepat waktu', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '1,48', ' -   ', 'Ringan'),
(188, 'PERENCANAAN, TI DAN PELAPORAN', 'Adanya uraian Tugas masing-masing unit', 'Area 2,5', '1. Sudah ada keseluruhan\n2. Sudah dilaksanakan\n3. Sudah dilakukan monitoring\n4. Sudah dievaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2  item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'DOCUMENT SYSTEM', '', '2,8', ' -   ', 'Sedang'),
(189, 'PERENCANAAN, TI DAN PELAPORAN', 'Implementasi SOP', 'Area 2,5', '1. SOP telah dibuat sesuai dengan\n   Peraturan Sekretaris Mahkamah Agung\n   R.I Nomor 002 Tahun 2012 tentang\n   Pedoman Penyusunan SOP di\n   Lingkungan MA dan Badan Peradilan\n   yang berada di bawahnya\n2. Sudah dilaksanakan dan tepat waktu\n3. Sudah dilakukan monitoring\n4. Sudah dilakukan evaluasi', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(190, 'PERENCANAAN, TI DAN PELAPORAN', 'Satker sudah mengisi aplikasi monev smart setiap bulannya dan melaporkan kepada pimpinan.', 'Area 2,4,5', '1. Indikator kinerja telah mengikuti kaidah\n    SMART\n2. Pengisian data sudah dilakukan\n    secara tertib setiap bulan\n3. Sekretaris melakukan monitoring perbulan\n4. Sudah dievaluasi', ' 1  item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '2,3', ' -   ', 'Sedang'),
(191, 'PERENCANAAN, TI DAN PELAPORAN', 'Penyusunan RKAKL', 'Area 2,4,5', '1. Telah melihatkan pimpinan dan unit lain dalam penyusunan RKAKL\n2. ada instrumen TOR dan RAB \n3. Di input melalui aplikasi SAKTI\n4. sudah dilaksanakan monev', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '5', ' -   ', 'Berat'),
(192, 'PERENCANAAN, TI DAN PELAPORAN', 'Pelaporan Keuangan satker DIPA 01 dan 03  (berdasarkan PMK no.22/PMK.05/2016) sesuai dengan standard akutansi pemerintah yang berlaku. ', 'Area 2,4,5', '1. Adanya Neraca, \n2. Laporan Realisasi Anggaran (LRA), \n3. Laporan Oprasional (LO), \n4. Laporan Perubahan Equitas (LPE) dan \n5. catatan atas laporan keuangan (calk)', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  s.d 4 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PERFORMANCE RESULT', '', '8,5', ' -   ', 'Berat'),
(193, 'PERENCANAAN, TI DAN PELAPORAN', 'Layanan Hukum bagi masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014', 'Area 5,6', '1. Sudah melakukan inovasi untuk mengoptimalkan pelaksanaan layanan hukum pembebasan biaya perkara (prodeo) pada masyarakat kurang mampu berdasarkan PERMA No 1 Tahun 2014\n2. Sudah melakukan Sosialisasi sesuai SE Dirjen Badilum Nomor 3 Tahun 2020 dan Nomor 2 Tahun 2022 baik secara Internal maupun Eksternal \n3. Pelaporan secara tertib menggunakan aplikasi dari Badilum\n4. Sudah dilaksanakan monev', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'STRATEGIC PLANNING', '', '5', ' -   ', 'Berat'),
(194, 'PERENCANAAN, TI DAN PELAPORAN', 'Kepatuhan Backup data sesuai Instruksi Dirjen Badilum Nomor 3102/DJU/SK/HM02.3/9/2019', 'Area 2,5,6', '1. Melakukan backup data minimal\n    1x dalam satu hari\n2. Melakukan singkronisasi ke PT\n    minimal 1x dalam satu hari\n3. Melakukan singkronisasi ke MA\n    minimal 1x dalam satu hari\n4. Melakukan monitoring dan evaluasi\n    terhadap backup data ', '1 item pada opsi \"A\" tidak terpenuhi', '2 item pada opsi \"A\" tidak terpenuhi', '3  item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'PROCESS MANAGEMENT', '', '3,5', ' -   ', 'Berat'),
(195, 'PERENCANAAN, TI DAN PELAPORAN', 'Standarisasi website pengadilan (Surat Dirjen Badilum No.362/DJU/HM.02.3/IV/2015\nMenindaklanjuti launching Pedoman Rancangan dan Prinsip Aksebilitas Website Pengadilan oleh Ketua MA-RI pada tanggal 17 Maret 2015)', 'Area 2,6\n', '1. Tampilan website menggunakan template latar\n     belakang merah sesuai ketentuan\n2. Alamat Website menggunakan domain resmi\n    pemerintahan\n3. Web dapat diakses kaum disabilitas\n4. Data selalu terupdate (termasuk profil\n    pengadilan dan berita)\n5. Keterbukaan informasi :\n    - Profil (struktur organisasi,LHKPN,dll)\n    - Pelayanan dasar/standar pelayanan\n      (prosedur beracara,biaya penyelesaian\n      perkara, agenda sidang)\n    - Hak masyarakat (hak bantuan hukum dan\n      biaya perkara cuma-cuma,dll)\n    - Prosedur pengaduan\n    - Ringkasan LKjIP\n    - LRA dan RKAKL\n6. Publikasi IKM, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017 \n7. Publikasi IPAK, format sesuai dengan\n    Lampiran IV Permenpan  RB No 14 tahun\n    2017', '1-2 item pada opsi \"A\" tidak terpenuhi', '3-4 item pada opsi \"A\" tidak terpenuhi', '5-6 item pada opsi \"A\" tidak terpenuhi', 'Belum Terpenuhi Seluruhnya', '', 'CUSTOMER FOCUS', '', '8', ' -   ', 'Berat');
